

help:
	$(info )
	$(info ---------------------------------------------------------------------------------)
	$(info !																				)
	$(info ! Wywolania make:																)
	$(info !   1. Przeprowadzenie symulacji VERILOG modelu ktory jest w katalogu ./MODEL	)
	$(info !      a TESTBENCH z pobudzeniami znajduje sie w katalogu ./TESTBENCH			)
	$(info ! 																				)
	$(info !            make sim_model 														)
	$(info ! 																				)
	$(info !																				)
	$(info ---------------------------------------------------------------------------------)
	$(info )

sim_model:
		make sim_model -C ./WORK -f Makefile.sim
		
.PHONY: help

