
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jan 16 2025 11:04:45 CET (Jan 16 2025 10:04:45 UTC)

// Verification Directory fv/EXE 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module EXE(i_oper, i_reg0, i_reg1, i_reg2, i_data2, i_data, i_imm,
     i_clk, i_rsn, o_flag, o_data);
  input [2:0] i_oper;
  input [3:0] i_reg0, i_reg1, i_reg2;
  input [5:0] i_data2, i_data;
  input i_imm, i_clk, i_rsn;
  output [3:0] o_flag;
  output [5:0] o_data;
  wire [2:0] i_oper;
  wire [3:0] i_reg0, i_reg1, i_reg2;
  wire [5:0] i_data2, i_data;
  wire i_imm, i_clk, i_rsn;
  wire [3:0] o_flag;
  wire [5:0] o_data;
  wire n_1884, n_1885, n_1886, n_1887, n_1888, n_1889, n_1890, n_1891;
  wire n_1892, n_1893, n_1894, n_1895, n_1896, n_1897, n_1898, n_1899;
  wire n_1900, n_1901, n_1902, n_1903, n_1904, n_1905, n_1906, n_1907;
  wire n_1908, n_1909, n_1910, n_1911, n_1912, n_1913, n_1914, n_1915;
  wire n_1916, n_1917, n_1918, n_1919, n_1920, n_1921, n_1922, n_1923;
  wire n_1924, n_1925, n_1926, n_1927, n_1928, n_1929, n_1930, n_1931;
  wire n_1932, n_1933, n_1934, n_1935, n_1936, n_1937, n_1938, n_1939;
  wire n_1940, n_1941, n_1942, n_1943, n_1944, n_1945, n_1946, n_1947;
  wire n_1948, n_1949, n_1950, n_1951, n_1952, n_1953, n_1954, n_1955;
  wire n_1956, n_1957, n_1958, n_1959, n_1960, n_1961, n_1962, n_1963;
  wire n_1964, n_1965, n_1966, n_1969, n_1970, n_1971, n_1972, n_1973;
  wire n_1974, n_1975, n_1977, n_1978, n_1979, n_1980, n_1981, n_1982;
  wire n_1983, n_1984, n_1986, n_1987, n_1989, n_1991, n_1993, n_1995;
  wire n_1997, n_2000, n_2004, n_2008, n_2012, n_2017, n_2018, n_2022;
  wire n_2023, n_2024, n_2025, n_2035, n_2036, n_2041, n_2042, n_2043;
  wire n_2044, n_2045, n_2056, n_2057, n_2058, n_2059, n_2060, n_2061;
  wire n_2062, n_2063, n_2064, n_2065, n_2066, n_2067, n_2068, n_2069;
  wire n_2070, n_2071, n_2072, n_2073, n_2074, n_2075, n_2076, n_2081;
  wire n_2082, n_2087, n_2088, n_2091, n_2094, n_2097, n_2106, n_2107;
  wire n_2108, n_2109, n_2118, n_2119, n_2120, n_2121, n_2130, n_2131;
  wire n_2132, n_2133, n_2142, n_2143, n_2144, n_2145, n_2154, n_2155;
  wire n_2156, n_2157, n_2166, n_2167, n_2168, n_2169, n_2178, n_2179;
  wire n_2180, n_2181, n_2184, n_2187, n_2190, n_2193, n_2208, n_2209;
  wire n_2210, n_2211, n_2212, n_2213, n_2214, n_2227, n_2228, n_2229;
  wire n_2230, n_2231, n_2232, n_2247, n_2248, n_2249, n_2250, n_2251;
  wire n_2252, n_2253, n_2266, n_2267, n_2268, n_2269, n_2270, n_2271;
  wire n_2286, n_2287, n_2288, n_2289, n_2290, n_2291, n_2292, n_2305;
  wire n_2306, n_2307, n_2308, n_2309, n_2310, n_2325, n_2326, n_2327;
  wire n_2328, n_2329, n_2330, n_2331, n_2344, n_2345, n_2346, n_2347;
  wire n_2348, n_2349, n_2364, n_2365, n_2366, n_2367, n_2368, n_2369;
  wire n_2370, n_2383, n_2384, n_2385, n_2386, n_2387, n_2388, n_2401;
  wire n_2402, n_2403, n_2404, n_2405, n_2406, n_2415, n_2416, n_2417;
  wire n_2418, n_2427, n_2428, n_2429, n_2430, n_2463, n_2464, n_2465;
  wire n_2466, n_2467, n_2468, n_2469, n_2470, n_2471, n_2472, n_2473;
  wire n_2474, n_2475, n_2476, n_2477, n_2478, n_2511, n_2512, n_2513;
  wire n_2514, n_2515, n_2516, n_2517, n_2518, n_2519, n_2520, n_2521;
  wire n_2522, n_2523, n_2524, n_2525, n_2526, n_2559, n_2560, n_2561;
  wire n_2562, n_2563, n_2564, n_2565, n_2566, n_2567, n_2568, n_2569;
  wire n_2570, n_2571, n_2572, n_2573, n_2574, n_2597, n_2598, n_2599;
  wire n_2600, n_2601, n_2602, n_2603, n_2604, n_2605, n_2606, n_2607;
  wire n_2630, n_2631, n_2632, n_2633, n_2634, n_2635, n_2636, n_2637;
  wire n_2638, n_2639, n_2640, n_2673, n_2674, n_2675, n_2676, n_2677;
  wire n_2678, n_2679, n_2680, n_2681, n_2682, n_2683, n_2684, n_2685;
  wire n_2686, n_2687, n_2688, n_2721, n_2722, n_2723, n_2724, n_2725;
  wire n_2726, n_2727, n_2728, n_2729, n_2730, n_2731, n_2732, n_2733;
  wire n_2734, n_2735, n_2736, n_2751, n_2752, n_2753, n_2754, n_2755;
  wire n_2756, n_2757, n_2780, n_2781, n_2782, n_2783, n_2784, n_2785;
  wire n_2786, n_2787, n_2788, n_2789, n_2790, n_2813, n_2814, n_2815;
  wire n_2816, n_2817, n_2818, n_2819, n_2820, n_2821, n_2822, n_2823;
  wire n_2846, n_2847, n_2848, n_2849, n_2850, n_2851, n_2852, n_2853;
  wire n_2854, n_2855, n_2856, n_2879, n_2880, n_2881, n_2882, n_2883;
  wire n_2884, n_2885, n_2886, n_2887, n_2888, n_2889, n_2898, n_2899;
  wire n_2900, n_2901, n_2904, n_2907, n_2912, n_2913, n_2918, n_2919;
  wire n_2924, n_2925, n_2928, n_2933, n_2934, n_2939, n_2940, n_2945;
  wire n_2946, n_2951, n_2952, n_2964, n_2969, n_2970, n_2975, n_2976;
  wire n_2985, n_2986, n_2987, n_2988, n_2999, n_3000, n_3001, n_3002;
  wire n_3003, n_3006, n_3013, n_3014, n_3015, n_3022, n_3023, n_3024;
  wire n_3027, n_3030, n_3037, n_3038, n_3039, n_3046, n_3047, n_3048;
  wire n_3057, n_3058, n_3059, n_3060, n_3065, n_3066, n_3074, n_3075;
  wire n_3078, n_3083, n_3084, n_3089, n_3090, n_3095, n_3096, n_3101;
  wire n_3102, n_3110, n_3111, n_3140, n_3141, n_3142, n_3143, n_3144;
  wire n_3145, n_3146, n_3147, n_3148, n_3149, n_3150, n_3151, n_3152;
  wire n_3153, n_3180, n_3181, n_3182, n_3183, n_3184, n_3185, n_3186;
  wire n_3187, n_3188, n_3189, n_3190, n_3191, n_3192, n_3195, n_3198;
  wire n_3203, n_3204, n_3213, n_3214, n_3215, n_3216, n_3223, n_3224;
  wire n_3225, n_3246, n_3247, n_3248, n_3249, n_3250, n_3251, n_3252;
  wire n_3253, n_3254, n_3255, n_3276, n_3277, n_3278, n_3279, n_3280;
  wire n_3281, n_3282, n_3283, n_3284, n_3285, n_3302, n_3303, n_3304;
  wire n_3305, n_3306, n_3307, n_3308, n_3309, n_3328, n_3329, n_3330;
  wire n_3331, n_3332, n_3333, n_3334, n_3335, n_3336, n_3343, n_3344;
  wire n_3345, n_3352, n_3353, n_3354, n_3359, n_3360, n_3365, n_3366;
  wire n_3632, n_3633, n_3634, n_3635, n_3636, n_3637, n_3638, n_3639;
  wire n_3640, n_3641, n_3642, n_3643, n_3644, n_3645, n_3646, n_3647;
  wire n_3648, n_3649, n_3650, n_3651, n_3652, n_3653, n_3654, n_3655;
  wire regs2_RRR_1_0, regs2_RRR_1_1, regs2_RRR_1_2, regs2_RRR_1_3,
       regs2_RRR_1_4, regs2_RRR_1_5, regs2_RRR_2_0, regs2_RRR_2_1;
  wire regs2_RRR_2_2, regs2_RRR_2_3, regs2_RRR_2_4, regs2_RRR_2_5,
       regs2_RRR_3_0, regs2_RRR_3_1, regs2_RRR_3_2, regs2_RRR_3_3;
  wire regs2_RRR_3_4, regs2_RRR_3_5, regs2_RRR_4_0, regs2_RRR_4_1,
       regs2_RRR_4_2, regs2_RRR_4_3, regs2_RRR_4_4, regs2_RRR_4_5;
  wire regs2_RRR_5_0, regs2_RRR_5_1, regs2_RRR_5_2, regs2_RRR_5_3,
       regs2_RRR_5_4, regs2_RRR_5_5, regs2_RRR_6_0, regs2_RRR_6_1;
  wire regs2_RRR_6_2, regs2_RRR_6_3, regs2_RRR_6_4, regs2_RRR_6_5,
       regs2_RRR_7_0, regs2_RRR_7_1, regs2_RRR_7_2, regs2_RRR_7_3;
  wire regs2_RRR_7_4, regs2_RRR_7_5, regs2_RRR_8_0, regs2_RRR_8_1,
       regs2_RRR_8_2, regs2_RRR_8_3, regs2_RRR_8_4, regs2_RRR_8_5;
  wire regs2_RRR_9_0, regs2_RRR_9_1, regs2_RRR_9_2, regs2_RRR_9_3,
       regs2_RRR_9_4, regs2_RRR_9_5, regs2_RRR_10_0, regs2_RRR_10_1;
  wire regs2_RRR_10_2, regs2_RRR_10_3, regs2_RRR_10_4, regs2_RRR_10_5,
       regs2_RRR_11_0, regs2_RRR_11_1, regs2_RRR_11_2, regs2_RRR_11_3;
  wire regs2_RRR_11_4, regs2_RRR_11_5, regs2_n_115, regs2_n_117,
       regs2_n_119, regs2_n_121, regs2_n_123, regs2_n_125;
  wire regs2_n_127, regs2_n_129, regs2_n_131, regs2_n_133, regs2_n_135,
       regs2_rc_gclk, regs2_rc_gclk_286, regs2_rc_gclk_288;
  wire regs2_rc_gclk_290, regs2_rc_gclk_292, regs2_rc_gclk_294,
       regs2_rc_gclk_296, regs2_rc_gclk_298, regs2_rc_gclk_300,
       regs2_rc_gclk_302, regs2_rc_gclk_304;
  assign o_data[5] = o_flag[0];
  RC_CG_MOD regs2_RC_CG_HIER_INST0(.enable (regs2_n_135), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk), .test (1'b0));
  RC_CG_MOD_1 regs2_RC_CG_HIER_INST1(.enable (regs2_n_115), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_286), .test (1'b0));
  RC_CG_MOD_2 regs2_RC_CG_HIER_INST2(.enable (regs2_n_117), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_288), .test (1'b0));
  RC_CG_MOD_3 regs2_RC_CG_HIER_INST3(.enable (regs2_n_119), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_290), .test (1'b0));
  RC_CG_MOD_4 regs2_RC_CG_HIER_INST4(.enable (regs2_n_121), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_292), .test (1'b0));
  RC_CG_MOD_5 regs2_RC_CG_HIER_INST5(.enable (regs2_n_123), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_294), .test (1'b0));
  RC_CG_MOD_6 regs2_RC_CG_HIER_INST6(.enable (regs2_n_125), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_296), .test (1'b0));
  RC_CG_MOD_7 regs2_RC_CG_HIER_INST7(.enable (regs2_n_127), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_298), .test (1'b0));
  RC_CG_MOD_8 regs2_RC_CG_HIER_INST8(.enable (regs2_n_129), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_300), .test (1'b0));
  RC_CG_MOD_9 regs2_RC_CG_HIER_INST9(.enable (regs2_n_131), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_302), .test (1'b0));
  RC_CG_MOD_10 regs2_RC_CG_HIER_INST10(.enable (regs2_n_133), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_304), .test (1'b0));
  not g5347 (o_flag[1], n_1993);
  nand g5587 (n_2043, n_1949, n_1952);
  or g5590 (n_2044, n_1979, n_1982);
  or g5683 (n_2058, n_1908, wc);
  not gc (wc, n_1922);
  or g5685 (n_2059, n_1925, wc0);
  not gc0 (wc0, n_1944);
  or g6252 (n_1939, n_2057, n_2045);
  nand g6583 (o_flag[3], n_3353, n_3354);
  or g6585 (n_1993, wc1, o_flag[0]);
  not gc1 (wc1, n_2018);
  or g6588 (n_2018, n_3345, o_data[1]);
  or g6589 (n_3345, n_3344, o_data[0]);
  or g6590 (n_3344, n_3343, o_data[2]);
  or g6591 (n_3343, o_data[4], o_data[3]);
  or g6592 (o_data[1], n_3335, n_3336);
  or g6593 (o_data[3], n_3254, n_3255);
  or g6594 (o_data[2], n_3284, n_3285);
  or g6595 (o_data[0], n_3308, n_3309);
  nand g6596 (n_3254, n_3250, n_3251);
  nand g6597 (n_3284, n_3280, n_3281);
  nand g6598 (n_3335, n_3331, n_3332);
  nand g6603 (n_1984, n_3203, n_3204);
  or g6605 (n_1987, n_3216, wc2);
  not gc2 (wc2, n_2023);
  or g6606 (n_1991, n_3366, wc3);
  not gc3 (wc3, n_2023);
  or g6607 (n_1989, n_3225, wc4);
  not gc4 (wc4, n_2023);
  nand g6608 (n_3216, n_3214, n_3215);
  nand g6611 (n_3366, n_3365, n_2024);
  or g6613 (o_flag[0], n_3191, n_3192);
  or g6614 (n_3215, n_3213, n_1983);
  or g6615 (n_3365, n_3198, wc5);
  not gc5 (wc5, n_2069);
  or g6616 (n_2017, n_3198, n_1982);
  nand g6617 (n_3225, n_3223, n_3224);
  or g6620 (n_3198, n_1981, n_1983);
  or g6621 (n_2023, wc6, n_1962);
  not gc6 (wc6, n_1981);
  or g6622 (n_3192, n_3189, n_3190);
  or g6623 (n_1981, n_3195, n_1978);
  or g6624 (o_data[4], n_3152, n_3153);
  nand g6625 (n_3189, n_3183, n_3184);
  or g6628 (n_3195, n_1973, n_1954);
  nand g6629 (n_3632, n_1971, n_1972);
  or g6630 (n_3633, n_1971, n_1972);
  nand g6631 (n_1973, n_3632, n_3633);
  nand g6632 (n_3149, n_3142, n_3143);
  or g6633 (n_3255, n_3252, n_3253);
  or g6634 (n_3153, n_3150, n_3151);
  nand g6637 (n_1972, n_3101, n_3102);
  nand g6638 (n_3253, n_3248, n_3249);
  nand g6639 (n_3190, n_3185, n_3186);
  nand g6640 (n_3101, n_1946, n_2043);
  nand g6641 (n_3151, n_3146, n_3147);
  nand g6642 (n_3634, n_1946, n_1953);
  or g6643 (n_3635, n_1946, n_1953);
  nand g6644 (n_1954, n_3634, n_3635);
  or g6645 (n_3285, n_3282, n_3283);
  or g6646 (n_3183, wc7, n_1962);
  not gc7 (wc7, n_2076);
  nand g6647 (n_3334, n_3329, n_3330);
  or g6648 (n_2076, n_3060, wc8);
  not gc8 (wc8, n_1897);
  nand g6649 (n_3308, n_3304, n_3305);
  nand g6650 (n_3282, n_3276, n_3277);
  nand g6651 (n_3252, n_3246, n_3247);
  nand g6654 (n_2071, n_3110, n_3111);
  nand g6655 (n_1946, n_3095, n_3096);
  or g6656 (n_3281, n_1955, n_2022);
  or g6659 (n_3142, wc9, n_1952);
  not gc9 (wc9, n_2075);
  or g6660 (n_3329, wc10, n_1935);
  not gc10 (wc10, n_2073);
  nand g6661 (n_2056, n_3002, n_3003);
  nand g6663 (n_3150, n_3144, n_3145);
  nand g6664 (n_3095, n_2058, n_1945);
  or g6665 (n_3305, wc11, n_1928);
  not gc11 (wc11, n_1965);
  or g6667 (n_3224, wc12, n_2024);
  not gc12 (wc12, n_2044);
  nand g6671 (n_1978, n_3636, n_3637);
  or g6672 (n_2073, n_3039, n_1965);
  nand g6673 (n_2065, n_3074, n_3075);
  or g6674 (n_3111, n_2044, n_1952);
  nand g6675 (n_3283, n_3278, n_3279);
  nand g6676 (n_3191, n_3187, n_3188);
  or g6677 (n_3214, wc13, n_1962);
  not gc13 (wc13, n_2066);
  or g6678 (n_3060, n_3059, n_1965);
  or g6679 (n_3110, wc14, n_1983);
  not gc14 (wc14, n_2070);
  or g6680 (n_2075, n_3048, n_1965);
  or g6681 (n_2022, n_3360, wc15);
  not gc15 (wc15, n_1937);
  nand g6682 (n_1965, n_2025, n_1964);
  or g6683 (n_3075, n_1979, n_1952);
  or g6684 (n_3003, n_3001, n_1962);
  nand g6685 (n_2042, n_2987, n_2988);
  or g6686 (n_2066, wc16, n_1983);
  not gc16 (wc16, n_3078);
  or g6690 (n_3187, n_3181, wc17);
  not gc17 (wc17, n_1924);
  nand g6691 (n_2069, n_3083, n_3084);
  nand g6693 (n_1945, n_3065, n_3066);
  or g6696 (n_3185, n_1952, n_1977);
  nand g6697 (n_2070, n_3089, n_3090);
  or g6698 (n_3360, n_3359, n_1924);
  or g6700 (n_3145, n_1921, n_1977);
  or g6702 (n_1964, n_3006, n_1896);
  or g6703 (n_2988, n_2986, n_1884);
  or g6705 (n_1977, n_1957, n_1959);
  or g6706 (n_3359, n_2928, n_1959);
  nand g6707 (n_3090, n_1986, n_1982);
  or g6708 (n_3089, n_1935, n_1982);
  or g6709 (n_3147, n_3140, n_1959);
  nand g6710 (n_3078, n_1979, n_1982);
  nand g6711 (n_3065, n_2059, n_1940);
  or g6713 (n_3083, n_1943, n_1982);
  nand g6714 (n_3084, n_1980, n_1982);
  or g6716 (n_3181, n_3180, n_1959);
  or g6717 (n_3001, n_3000, wc18);
  not gc18 (wc18, i_oper[0]);
  nand g6720 (n_1983, n_3638, n_3639);
  or g6721 (n_2986, n_1958, i_oper[0]);
  nand g6722 (n_1953, n_2043, n_3027);
  nand g6723 (n_3640, n_2041, n_1932);
  or g6724 (n_3641, n_2041, n_1932);
  nand g6725 (n_1982, n_3640, n_3641);
  or g6726 (n_1959, n_1886, n_1958);
  or g6727 (n_3006, n_1886, wc19);
  not gc19 (wc19, n_1958);
  nand g6728 (n_1940, n_1939, n_3030);
  or g6729 (n_3000, n_1958, i_oper[1]);
  nand g6732 (n_2035, n_2969, n_2970);
  nand g6733 (n_2012, n_1962, n_2901);
  nand g6734 (n_3030, n_1932, n_1938);
  nand g6735 (n_2036, n_2975, n_2976);
  nand g6736 (n_2041, n_1938, n_1939);
  or g6737 (n_2901, n_2900, wc20);
  not gc20 (wc20, n_1943);
  nand g6738 (n_1986, n_2951, n_2952);
  or g6740 (n_2970, n_1908, n_1922);
  nand g6741 (n_2969, n_1908, n_1921);
  nand g6742 (n_1980, n_2945, n_2946);
  nand g6743 (n_1938, n_2057, n_2045);
  nand g6744 (n_1932, n_2939, n_2940);
  or g6745 (n_3102, n_1949, n_1952);
  or g6746 (n_3096, wc21, n_1921);
  not gc21 (wc21, n_1908);
  nand g6747 (n_3307, n_3302, n_3303);
  nand g6748 (n_3642, n_1969, n_1970);
  or g6749 (n_3643, n_1969, n_1970);
  nand g6750 (n_1971, n_3642, n_3643);
  or g6751 (n_2964, n_1931, n_1957);
  or g6752 (n_3066, wc22, n_1943);
  not gc22 (wc22, n_1925);
  or g6753 (n_2976, n_1925, n_1944);
  nand g6754 (n_2975, n_1925, n_1943);
  or g6755 (n_3644, wc23, n_1924);
  not gc23 (wc23, n_1898);
  or g6756 (n_3645, n_1898, wc24);
  not gc24 (wc24, n_1924);
  nand g6757 (n_1925, n_3644, n_3645);
  or g6758 (n_2952, n_1979, n_1943);
  or g6759 (n_2951, wc25, n_1921);
  not gc25 (wc25, n_1979);
  or g6760 (n_3180, n_1956, wc26);
  not gc26 (wc26, n_1974);
  nand g6761 (n_3646, n_1898, n_1937);
  or g6762 (n_3647, n_1898, n_1937);
  nand g6763 (n_2057, n_3646, n_3647);
  or g6764 (n_2900, n_2899, wc27);
  not gc27 (wc27, n_1921);
  or g6765 (n_3140, n_1955, n_1956);
  nand g6766 (n_3276, n_2068, n_1924);
  nand g6767 (n_3302, n_2072, n_1931);
  or g6768 (n_2946, n_1979, n_1921);
  or g6769 (n_2945, wc28, n_1952);
  not gc28 (wc28, n_1979);
  or g6770 (n_3648, wc29, n_1907);
  not gc29 (wc29, n_1898);
  or g6771 (n_3649, n_1898, wc30);
  not gc30 (wc30, n_1907);
  nand g6772 (n_1908, n_3648, n_3649);
  or g6773 (n_3002, n_2999, wc31);
  not gc31 (wc31, n_1896);
  or g6774 (n_1957, n_1956, n_1924);
  nand g6775 (n_3246, n_2061, n_1907);
  nand g6776 (n_3650, n_1896, n_1898);
  or g6777 (n_3651, n_1896, n_1898);
  nand g6778 (n_1970, n_3650, n_3651);
  nand g6779 (n_3652, n_1948, n_1898);
  or g6780 (n_3653, n_1948, n_1898);
  nand g6781 (n_1949, n_3652, n_3653);
  or g6783 (n_2939, wc32, n_1931);
  not gc32 (wc32, n_1898);
  or g6784 (n_3148, n_3141, n_1885);
  nand g6785 (n_3048, n_3046, n_3047);
  nand g6786 (n_2068, n_2025, n_2907);
  nand g6787 (n_1975, n_2924, n_2925);
  or g6788 (n_1898, wc33, i_oper[0]);
  not gc33 (wc33, n_1897);
  or g6789 (n_2999, n_1969, i_oper[0]);
  or g6790 (n_1956, n_2928, n_1937);
  or g6791 (n_2940, n_1929, wc34);
  not gc34 (wc34, n_1931);
  nand g6792 (n_3024, n_3022, n_3023);
  nand g6793 (n_3015, n_3013, n_3014);
  or g6794 (n_3303, n_1885, n_1955);
  or g6795 (n_3144, n_1897, n_1962);
  nand g6796 (n_2061, n_2025, n_2904);
  nand g6797 (n_1963, n_2918, n_2919);
  nand g6798 (n_3059, n_3057, n_3058);
  nand g6799 (n_1974, n_2933, n_2934);
  or g6800 (n_3188, n_3182, n_1885);
  nand g6801 (n_3039, n_3037, n_3038);
  or g6802 (n_3333, n_3328, n_1885);
  nand g6803 (n_2072, n_2912, n_2913);
  nand g6804 (n_3654, n_1929, n_1931);
  or g6805 (n_3655, n_1929, n_1931);
  nand g6806 (n_1979, n_3654, n_3655);
  or g6807 (n_2899, n_2898, wc35);
  not gc35 (wc35, n_1952);
  nand g6808 (n_3328, n_1935, n_1937);
  or g6809 (n_3037, n_1885, n_1937);
  nand g6812 (n_3182, n_1896, n_1962);
  or g6813 (n_2933, n_1931, n_1935);
  or g6814 (n_3057, n_1885, n_1896);
  or g6816 (n_2934, n_1928, wc36);
  not gc36 (wc36, n_1931);
  nand g6817 (n_3141, n_1948, n_1952);
  or g6818 (n_1969, n_1884, n_1962);
  or g6820 (n_2928, n_1948, n_1907);
  or g6823 (n_1955, n_1931, n_1928);
  or g6824 (n_2924, n_1921, n_1931);
  or g6827 (n_3022, n_1885, n_1924);
  or g6828 (n_2912, n_1966, n_1928);
  or g6830 (n_2918, n_1931, n_1943);
  nand g6831 (n_2898, n_1928, n_1935);
  or g6832 (n_3013, n_1885, n_1907);
  or g6833 (n_2045, n_1884, n_1935);
  or g6835 (n_2904, wc37, n_1885);
  not gc37 (wc37, n_1921);
  or g6836 (n_1929, n_1884, n_1928);
  or g6837 (n_1944, n_1884, n_1943);
  or g6838 (n_1922, n_1884, n_1921);
  or g6839 (n_3046, n_1885, n_1948);
  or g6840 (n_2907, wc38, n_1885);
  not gc38 (wc38, n_1943);
  or g6841 (n_1921, n_2856, wc39);
  not gc39 (wc39, n_1916);
  or g6842 (n_1952, n_2790, wc40);
  not gc40 (wc40, n_1916);
  or g6843 (n_1943, n_2889, wc41);
  not gc41 (wc41, n_1916);
  or g6844 (n_1924, n_2573, n_2574);
  or g6845 (n_1935, n_2640, wc42);
  not gc42 (wc42, n_1916);
  or g6846 (n_1896, n_2756, n_2757);
  or g6847 (n_1937, n_2687, n_2688);
  or g6848 (n_1928, n_2607, wc43);
  not gc43 (wc43, n_1916);
  or g6849 (n_1931, n_2735, n_2736);
  or g6850 (n_1907, n_2477, n_2478);
  or g6851 (n_1962, n_2823, wc44);
  not gc44 (wc44, n_1916);
  or g6852 (n_1948, n_2525, n_2526);
  or g6853 (n_2790, n_2788, n_2789);
  or g6854 (n_2640, n_2638, n_2639);
  or g6855 (n_2823, n_2821, n_2822);
  or g6856 (n_2574, n_2571, n_2572);
  or g6857 (n_2607, n_2605, n_2606);
  or g6858 (n_2478, n_2475, n_2476);
  or g6859 (n_2889, n_2887, n_2888);
  nand g6860 (n_2757, n_2754, n_2755);
  or g6861 (n_2856, n_2854, n_2855);
  or g6862 (n_2736, n_2733, n_2734);
  or g6863 (n_2688, n_2685, n_2686);
  or g6864 (n_2526, n_2523, n_2524);
  nand g6865 (n_2571, n_2565, n_2566);
  or g6866 (n_2639, n_2636, n_2637);
  or g6867 (n_2789, n_2786, n_2787);
  nand g6868 (n_2475, n_2469, n_2470);
  or g6869 (n_2822, n_2819, n_2820);
  or g6870 (n_2606, n_2603, n_2604);
  or g6871 (n_2855, n_2852, n_2853);
  nand g6872 (n_2733, n_2727, n_2728);
  or g6873 (n_2755, n_2751, i_reg1[2]);
  or g6874 (n_2888, n_2885, n_2886);
  nand g6875 (n_2756, n_2752, n_2753);
  nand g6876 (n_2685, n_2679, n_2680);
  nand g6877 (n_2523, n_2517, n_2518);
  nand g6878 (n_2854, n_2850, n_2851);
  nand g6879 (n_2886, n_2881, n_2882);
  or g6880 (n_2679, n_1895, n_1936);
  nand g6881 (n_2821, n_2817, n_2818);
  or g6884 (n_2735, n_2731, n_2732);
  or g6885 (n_2687, n_2683, n_2684);
  nand g6887 (n_2788, n_2784, n_2785);
  or g6888 (n_2727, n_1895, n_1930);
  nand g6889 (n_2638, n_2634, n_2635);
  nand g6891 (n_2887, n_2883, n_2884);
  nand g6893 (n_2853, n_2848, n_2849);
  or g6894 (n_2469, n_1895, n_1899);
  or g6895 (n_2517, n_1895, n_1947);
  nand g6896 (n_2604, n_2599, n_2600);
  nand g6897 (n_2637, n_2632, n_2633);
  nand g6898 (n_2820, n_2815, n_2816);
  or g6899 (n_2477, n_2473, n_2474);
  or g6900 (n_2525, n_2521, n_2522);
  or g6902 (n_2565, n_1895, n_1923);
  or g6903 (n_2573, n_2569, n_2570);
  or g6904 (n_2753, n_1888, wc45);
  not gc45 (wc45, n_1894);
  nand g6905 (n_2605, n_2601, n_2602);
  nand g6906 (n_2787, n_2782, n_2783);
  or g6907 (n_1923, n_2253, i_reg1[2]);
  nand g6908 (n_2522, n_2515, n_2516);
  or g6910 (n_2602, n_1927, wc46);
  not gc46 (wc46, i_reg0[2]);
  or g6911 (n_2752, n_1887, wc47);
  not gc47 (wc47, n_1892);
  nand g6912 (n_2568, n_2559, n_2560);
  nand g6913 (n_2570, n_2563, n_2564);
  nand g6914 (n_2520, n_2511, n_2512);
  nand g6915 (n_2569, n_2561, n_2562);
  or g6916 (n_2599, n_1918, n_1926);
  or g6917 (n_2632, n_1918, n_1933);
  nand g6918 (n_2731, n_2723, n_2724);
  or g6919 (n_2785, n_1951, wc48);
  not gc48 (wc48, i_reg0[2]);
  nand g6920 (n_2730, n_2721, n_2722);
  or g6921 (n_2635, n_1934, wc49);
  not gc49 (wc49, i_reg0[2]);
  or g6922 (n_1899, n_2214, i_reg1[2]);
  or g6923 (n_1930, n_2292, i_reg1[2]);
  nand g6924 (n_2521, n_2513, n_2514);
  nand g6925 (n_2732, n_2725, n_2726);
  nand g6926 (n_2472, n_2463, n_2464);
  nand g6927 (n_2473, n_2465, n_2466);
  nand g6928 (n_2682, n_2673, n_2674);
  or g6929 (n_2881, n_1918, n_1941);
  or g6930 (n_2851, n_1914, wc50);
  not gc50 (wc50, i_reg0[2]);
  or g6931 (n_1936, n_2331, i_reg1[2]);
  or g6932 (n_2782, n_1918, n_1950);
  or g6933 (n_2818, n_1961, wc51);
  not gc51 (wc51, i_reg0[2]);
  or g6934 (n_2848, n_1912, n_1918);
  or g6936 (n_2884, n_1942, wc52);
  not gc52 (wc52, i_reg0[2]);
  nand g6937 (n_2684, n_2677, n_2678);
  nand g6938 (n_2683, n_2675, n_2676);
  or g6939 (n_2815, n_1918, n_1960);
  or g6940 (n_1947, n_2370, i_reg1[2]);
  nand g6941 (n_2474, n_2467, n_2468);
  or g6942 (n_2512, wc53, n_1905);
  not gc53 (wc53, regs2_RRR_7_4);
  or g6943 (n_2292, n_2290, n_2291);
  or g6945 (n_2214, n_2212, n_2213);
  or g6946 (n_2514, wc54, n_1903);
  not gc54 (wc54, regs2_RRR_4_4);
  or g6947 (n_1942, n_2348, n_2349);
  or g6949 (n_2674, wc55, n_1905);
  not gc55 (wc55, regs2_RRR_7_1);
  or g6950 (n_2673, wc56, n_1906);
  not gc56 (wc56, regs2_RRR_5_1);
  or g6951 (n_2515, wc57, n_1902);
  not gc57 (wc57, regs2_RRR_2_4);
  nand g6952 (n_2885, n_2879, n_2880);
  nand g6953 (n_2852, n_2846, n_2847);
  or g6954 (n_2722, wc58, n_1905);
  not gc58 (wc58, regs2_RRR_7_0);
  or g6955 (n_2680, wc59, n_1900);
  not gc59 (wc59, regs2_RRR_1_1);
  or g6957 (n_2721, wc60, n_1906);
  not gc60 (wc60, regs2_RRR_5_0);
  or g6958 (n_1914, n_2231, n_2232);
  or g6959 (n_2723, wc61, n_1904);
  not gc61 (wc61, regs2_RRR_6_0);
  or g6960 (n_2331, n_2329, n_2330);
  or g6962 (n_2724, wc62, n_1903);
  not gc62 (wc62, regs2_RRR_4_0);
  or g6963 (n_2511, wc63, n_1906);
  not gc63 (wc63, regs2_RRR_5_4);
  nand g6964 (n_2418, n_2415, n_2416);
  or g6965 (n_2725, wc64, n_1902);
  not gc64 (wc64, regs2_RRR_2_0);
  or g6966 (n_1961, n_2405, n_2406);
  nand g6967 (n_2786, n_2780, n_2781);
  or g6968 (n_2468, wc65, n_1901);
  not gc65 (wc65, regs2_RRR_3_3);
  or g6970 (n_2467, wc66, n_1902);
  not gc66 (wc66, regs2_RRR_2_3);
  nand g6971 (n_2819, n_2813, n_2814);
  or g6972 (n_2678, wc67, n_1901);
  not gc67 (wc67, regs2_RRR_3_1);
  or g6973 (n_1934, n_2309, n_2310);
  or g6974 (n_2677, wc68, n_1902);
  not gc68 (wc68, regs2_RRR_2_1);
  or g6975 (n_2518, wc69, n_1900);
  not gc69 (wc69, regs2_RRR_1_4);
  nand g6976 (n_2636, n_2630, n_2631);
  or g6977 (n_1951, n_2387, n_2388);
  or g6978 (n_2676, wc70, n_1903);
  not gc70 (wc70, regs2_RRR_4_1);
  or g6979 (n_2675, wc71, n_1904);
  not gc71 (wc71, regs2_RRR_6_1);
  or g6981 (n_2728, wc72, n_1900);
  not gc72 (wc72, regs2_RRR_1_0);
  or g6982 (n_2560, wc73, n_1905);
  not gc73 (wc73, regs2_RRR_7_2);
  or g6983 (n_2559, wc74, n_1906);
  not gc74 (wc74, regs2_RRR_5_2);
  or g6984 (n_2466, wc75, n_1903);
  not gc75 (wc75, regs2_RRR_4_3);
  or g6986 (n_2566, wc76, n_1900);
  not gc76 (wc76, regs2_RRR_1_2);
  or g6987 (n_2465, wc77, n_1904);
  not gc77 (wc77, regs2_RRR_6_3);
  or g6988 (n_2370, n_2368, n_2369);
  or g6989 (n_2253, n_2251, n_2252);
  or g6990 (n_2464, wc78, n_1905);
  not gc78 (wc78, regs2_RRR_7_3);
  or g6991 (n_2463, wc79, n_1906);
  not gc79 (wc79, regs2_RRR_5_3);
  nand g6992 (n_2430, n_2427, n_2428);
  or g6993 (n_2726, wc80, n_1901);
  not gc80 (wc80, regs2_RRR_3_0);
  or g6994 (n_2513, wc81, n_1904);
  not gc81 (wc81, regs2_RRR_6_4);
  or g6995 (n_1927, n_2270, n_2271);
  or g6996 (n_2470, wc82, n_1900);
  not gc82 (wc82, regs2_RRR_1_3);
  or g6997 (n_2516, wc83, n_1901);
  not gc83 (wc83, regs2_RRR_3_4);
  or g6998 (n_2564, wc84, n_1901);
  not gc84 (wc84, regs2_RRR_3_2);
  or g6999 (n_2563, wc85, n_1902);
  not gc85 (wc85, regs2_RRR_2_2);
  nand g7000 (n_2603, n_2597, n_2598);
  or g7001 (n_2562, wc86, n_1903);
  not gc86 (wc86, regs2_RRR_4_2);
  or g7002 (n_2561, wc87, n_1904);
  not gc87 (wc87, regs2_RRR_6_2);
  or g7003 (n_1904, n_1888, n_1891);
  nand g7004 (n_2348, n_2344, n_2345);
  or g7005 (n_2783, regs2_RRR_8_4, n_1917);
  nand g7006 (n_2349, n_2346, n_2347);
  or g7007 (n_2849, regs2_RRR_8_3, n_1917);
  nand g7008 (n_2121, n_2118, n_2119);
  or g7009 (n_2879, regs2_RRR_10_2, n_1920);
  or g7010 (n_2880, regs2_RRR_11_2, n_1919);
  or g7011 (n_2847, regs2_RRR_11_3, n_1919);
  or g7012 (n_2846, regs2_RRR_10_3, n_1920);
  nand g7013 (n_2169, n_2166, n_2167);
  nand g7014 (n_2232, n_2229, n_2230);
  nand g7015 (n_2157, n_2154, n_2155);
  nand g7016 (n_2231, n_2227, n_2228);
  or g7017 (n_2882, regs2_RRR_8_2, n_1917);
  nand g7018 (n_2109, n_2106, n_2107);
  or g7019 (n_2850, regs2_RRR_9_3, n_1915);
  or g7020 (n_2634, regs2_RRR_9_1, n_1915);
  or g7021 (n_2781, regs2_RRR_11_4, n_1919);
  nand g7022 (n_2309, n_2305, n_2306);
  or g7023 (n_2780, regs2_RRR_10_4, n_1920);
  nand g7024 (n_2310, n_2307, n_2308);
  or g7025 (n_2630, regs2_RRR_10_1, n_1920);
  or g7026 (n_2631, regs2_RRR_11_1, n_1919);
  nand g7027 (n_2388, n_2385, n_2386);
  nand g7028 (n_2145, n_2142, n_2143);
  or g7029 (n_2633, regs2_RRR_8_1, n_1917);
  or g7030 (n_2601, regs2_RRR_9_0, n_1915);
  nand g7031 (n_2387, n_2383, n_2384);
  or g7032 (n_2784, regs2_RRR_9_4, n_1915);
  nand g7033 (n_2270, n_2266, n_2267);
  nand g7034 (n_2252, n_2249, n_2250);
  nand g7035 (n_2427, n_2064, i_reg1[1]);
  nand g7036 (n_2251, n_2247, n_2248);
  nand g7037 (n_2271, n_2268, n_2269);
  or g7038 (n_2597, regs2_RRR_10_0, n_1920);
  or g7039 (n_2598, regs2_RRR_11_0, n_1919);
  nand g7040 (n_2133, n_2130, n_2131);
  or g7041 (n_2600, regs2_RRR_8_0, n_1917);
  or g7042 (n_2817, regs2_RRR_9_5, n_1915);
  or g7043 (n_1905, n_1888, n_1890);
  nand g7044 (n_2405, n_2401, n_2402);
  or g7045 (n_1906, n_1888, n_1889);
  nand g7046 (n_2406, n_2403, n_2404);
  nand g7047 (n_2330, n_2327, n_2328);
  or g7048 (n_2415, wc88, i_reg1[1]);
  not gc88 (wc88, n_2062);
  nand g7049 (n_2329, n_2325, n_2326);
  or g7050 (n_2813, regs2_RRR_10_5, n_1920);
  or g7051 (n_2814, regs2_RRR_11_5, n_1919);
  or g7052 (n_1900, n_1889, n_1887);
  nand g7053 (n_2181, n_2178, n_2179);
  or g7054 (n_2816, regs2_RRR_8_5, n_1917);
  nand g7055 (n_2369, n_2366, n_2367);
  nand g7056 (n_2368, n_2364, n_2365);
  or g7057 (n_1901, n_1887, n_1890);
  nand g7058 (n_2213, n_2210, n_2211);
  nand g7061 (n_2212, n_2208, n_2209);
  or g7064 (n_1902, n_1887, n_1891);
  or g7077 (n_1903, n_1888, n_1893);
  nand g7078 (n_2291, n_2288, n_2289);
  nand g7079 (n_2290, n_2286, n_2287);
  or g7080 (n_2883, regs2_RRR_9_2, n_1915);
  or g7081 (n_2286, regs2_RRR_8_0, n_1893);
  or g7082 (n_2287, regs2_RRR_9_0, n_1889);
  or g7083 (n_2288, regs2_RRR_11_0, n_1890);
  or g7084 (n_2289, regs2_RRR_10_0, n_1891);
  or g7085 (n_2190, n_2004, wc89);
  not gc89 (wc89, i_reg2[3]);
  or g7086 (n_2208, regs2_RRR_8_3, n_1893);
  or g7087 (n_2209, regs2_RRR_9_3, n_1889);
  or g7088 (n_2210, regs2_RRR_11_3, n_1890);
  or g7089 (n_2211, regs2_RRR_10_3, n_1891);
  or g7090 (n_2403, wc90, n_1911);
  not gc90 (wc90, regs2_RRR_6_5);
  or g7091 (n_2325, regs2_RRR_8_1, n_1893);
  or g7092 (n_2326, regs2_RRR_9_1, n_1889);
  or g7093 (n_2416, wc91, n_1890);
  not gc91 (wc91, regs2_RRR_11_5);
  or g7094 (n_2327, regs2_RRR_11_1, n_1890);
  nand g7095 (n_2062, n_2081, n_2082);
  or g7096 (n_2404, wc92, n_1909);
  not gc92 (wc92, regs2_RRR_7_5);
  or g7097 (n_2180, wc93, n_1909);
  not gc93 (wc93, regs2_RRR_3_5);
  or g7098 (n_2417, wc94, n_1891);
  not gc94 (wc94, regs2_RRR_10_5);
  or g7099 (n_2178, wc95, n_1910);
  not gc95 (wc95, regs2_RRR_1_5);
  or g7100 (n_2328, regs2_RRR_10_1, n_1891);
  or g7101 (n_2179, wc96, n_1911);
  not gc96 (wc96, regs2_RRR_2_5);
  or g7102 (n_2247, regs2_RRR_8_2, n_1893);
  or g7103 (n_2248, regs2_RRR_9_2, n_1889);
  or g7104 (n_2428, wc97, n_1889);
  not gc97 (wc97, regs2_RRR_5_5);
  or g7105 (n_2249, regs2_RRR_11_2, n_1890);
  nand g7106 (n_2064, n_2087, n_2088);
  or g7107 (n_2193, n_2008, wc98);
  not gc98 (wc98, i_reg2[2]);
  or g7110 (n_2429, wc99, n_1893);
  not gc99 (wc99, regs2_RRR_4_5);
  or g7111 (n_2250, regs2_RRR_10_2, n_1891);
  or g7112 (n_2367, regs2_RRR_10_4, n_1891);
  or g7113 (n_2366, regs2_RRR_11_4, n_1890);
  or g7114 (n_2107, wc100, n_1890);
  not gc100 (wc100, regs2_RRR_3_5);
  or g7115 (n_2106, wc101, n_1889);
  not gc101 (wc101, regs2_RRR_1_5);
  or g7116 (n_2108, wc102, n_1891);
  not gc102 (wc102, regs2_RRR_2_5);
  or g7117 (n_1886, n_2091, i_oper[0]);
  or g7118 (n_2025, n_1885, i_oper[0]);
  or g7119 (n_2227, wc103, n_1913);
  not gc103 (wc103, regs2_RRR_4_3);
  or g7120 (n_2228, wc104, n_1910);
  not gc104 (wc104, regs2_RRR_5_3);
  or g7121 (n_1966, n_2091, wc105);
  not gc105 (wc105, i_oper[0]);
  or g7122 (n_2184, n_1997, wc106);
  not gc106 (wc106, i_reg2[3]);
  or g7123 (n_2229, wc107, n_1911);
  not gc107 (wc107, regs2_RRR_6_3);
  or g7124 (n_2230, wc108, n_1909);
  not gc108 (wc108, regs2_RRR_7_3);
  or g7125 (n_2365, regs2_RRR_9_4, n_1889);
  or g7126 (n_2120, wc109, n_1909);
  not gc109 (wc109, regs2_RRR_3_3);
  or g7127 (n_2118, wc110, n_1910);
  not gc110 (wc110, regs2_RRR_1_3);
  or g7128 (n_1887, n_2094, i_imm);
  or g7129 (n_2119, wc111, n_1911);
  not gc111 (wc111, regs2_RRR_2_3);
  or g7130 (n_2344, wc112, n_1913);
  not gc112 (wc112, regs2_RRR_4_2);
  or g7131 (n_2345, wc113, n_1910);
  not gc113 (wc113, regs2_RRR_5_2);
  or g7132 (n_2346, wc114, n_1911);
  not gc114 (wc114, regs2_RRR_6_2);
  or g7133 (n_1917, n_1913, wc115);
  not gc115 (wc115, i_reg0[3]);
  or g7134 (n_2347, wc116, n_1909);
  not gc116 (wc116, regs2_RRR_7_2);
  or g7135 (n_2156, wc117, n_1909);
  not gc117 (wc117, regs2_RRR_3_2);
  or g7136 (n_2154, wc118, n_1910);
  not gc118 (wc118, regs2_RRR_1_2);
  or g7137 (n_2167, wc119, n_1911);
  not gc119 (wc119, regs2_RRR_2_4);
  or g7138 (n_2166, wc120, n_1910);
  not gc120 (wc120, regs2_RRR_1_4);
  or g7139 (n_2168, wc121, n_1909);
  not gc121 (wc121, regs2_RRR_3_4);
  or g7140 (n_2364, regs2_RRR_8_4, n_1893);
  or g7141 (n_2155, wc122, n_1911);
  not gc122 (wc122, regs2_RRR_2_2);
  or g7142 (n_2305, wc123, n_1913);
  not gc123 (wc123, regs2_RRR_4_1);
  or g7143 (n_1919, n_1909, wc124);
  not gc124 (wc124, i_reg0[3]);
  or g7144 (n_2306, wc125, n_1910);
  not gc125 (wc125, regs2_RRR_5_1);
  or g7145 (n_1920, n_1911, wc126);
  not gc126 (wc126, i_reg0[3]);
  or g7146 (n_2307, wc127, n_1911);
  not gc127 (wc127, regs2_RRR_6_1);
  or g7147 (n_2308, wc128, n_1909);
  not gc128 (wc128, regs2_RRR_7_1);
  or g7148 (n_1888, n_2097, i_imm);
  or g7149 (n_2142, wc129, n_1910);
  not gc129 (wc129, regs2_RRR_1_1);
  or g7150 (n_2386, wc130, n_1909);
  not gc130 (wc130, regs2_RRR_7_4);
  or g7151 (n_2144, wc131, n_1909);
  not gc131 (wc131, regs2_RRR_3_1);
  or g7152 (n_2385, wc132, n_1911);
  not gc132 (wc132, regs2_RRR_6_4);
  or g7155 (n_2143, wc133, n_1911);
  not gc133 (wc133, regs2_RRR_2_1);
  or g7156 (n_2384, wc134, n_1910);
  not gc134 (wc134, regs2_RRR_5_4);
  or g7157 (n_2383, wc135, n_1913);
  not gc135 (wc135, regs2_RRR_4_4);
  or g7158 (n_2187, n_2000, wc136);
  not gc136 (wc136, i_reg2[2]);
  or g7159 (n_2266, wc137, n_1913);
  not gc137 (wc137, regs2_RRR_4_0);
  or g7160 (n_1915, n_1910, wc138);
  not gc138 (wc138, i_reg0[3]);
  or g7163 (n_2267, wc139, n_1910);
  not gc139 (wc139, regs2_RRR_5_0);
  or g7164 (n_2268, wc140, n_1911);
  not gc140 (wc140, regs2_RRR_6_0);
  or g7165 (n_2269, wc141, n_1909);
  not gc141 (wc141, regs2_RRR_7_0);
  or g7166 (n_2132, wc142, n_1909);
  not gc142 (wc142, regs2_RRR_3_0);
  or g7167 (n_2130, wc143, n_1910);
  not gc143 (wc143, regs2_RRR_1_0);
  or g7168 (n_2131, wc144, n_1911);
  not gc144 (wc144, regs2_RRR_2_0);
  or g7169 (n_2401, wc145, n_1913);
  not gc145 (wc145, regs2_RRR_4_5);
  or g7170 (n_2402, wc146, n_1910);
  not gc146 (wc146, regs2_RRR_5_5);
  nand g7171 (n_2729, i_data[0], i_imm);
  nand g7172 (n_2471, i_data[3], i_imm);
  nand g7173 (n_2082, regs2_RRR_9_5, i_reg1[0]);
  or g7174 (n_2081, wc147, i_reg1[0]);
  not gc147 (wc147, regs2_RRR_8_5);
  nand g7175 (n_2754, i_data[5], i_imm);
  nand g7176 (n_2681, i_data[1], i_imm);
  nand g7177 (n_2088, regs2_RRR_7_5, i_reg1[0]);
  or g7178 (n_2087, wc148, i_reg1[0]);
  not gc148 (wc148, regs2_RRR_6_5);
  nand g7179 (n_2567, i_data[2], i_imm);
  or g7180 (n_1884, i_oper[2], i_oper[1]);
  or g7181 (n_2091, i_oper[2], wc149);
  not gc149 (wc149, i_oper[1]);
  or g7182 (n_1885, wc150, i_oper[1]);
  not gc150 (wc150, i_oper[2]);
  nand g7183 (n_1916, i_reg0[2], i_reg0[3]);
  or g7184 (n_1918, i_reg0[2], i_reg0[3]);
  nand g7185 (n_1909, i_reg0[0], i_reg0[1]);
  or g7186 (n_1891, wc151, i_reg1[0]);
  not gc151 (wc151, i_reg1[1]);
  or g7187 (n_1913, i_reg0[0], i_reg0[1]);
  or g7188 (n_1910, i_reg0[1], wc152);
  not gc152 (wc152, i_reg0[0]);
  nand g7189 (n_2519, i_data[4], i_imm);
  or g7190 (n_1997, i_reg2[2], wc153);
  not gc153 (wc153, i_reg2[1]);
  or g7191 (n_2000, i_reg2[3], wc154);
  not gc154 (wc154, i_reg2[0]);
  or g7192 (n_1889, i_reg1[1], wc155);
  not gc155 (wc155, i_reg1[0]);
  or g7193 (n_1895, wc156, i_imm);
  not gc156 (wc156, i_reg1[3]);
  or g7194 (n_2004, i_reg2[1], i_reg2[2]);
  or g7195 (n_2008, i_reg2[0], i_reg2[3]);
  nand g7196 (n_1890, i_reg1[1], i_reg1[0]);
  or g7197 (n_2094, i_reg1[3], i_reg1[2]);
  or g7198 (n_1893, i_reg1[0], i_reg1[1]);
  or g7199 (n_2985, i_oper[2], wc157);
  not gc157 (wc157, i_oper[0]);
  or g7200 (n_2097, i_reg1[3], wc158);
  not gc158 (wc158, i_reg1[2]);
  or g7201 (n_1911, wc159, i_reg0[0]);
  not gc159 (wc159, i_reg0[1]);
  nor g7202 (regs2_n_133, n_2008, n_1997);
  nor g7203 (regs2_n_131, n_2000, n_1997);
  nor g7204 (regs2_n_135, n_2004, n_2000);
  and g7205 (regs2_n_115, i_reg2[0], wc160);
  not gc160 (wc160, n_2184);
  nor g7206 (regs2_n_117, n_2184, i_reg2[0]);
  nor g7207 (regs2_n_127, n_2187, i_reg2[1]);
  and g7208 (regs2_n_123, i_reg2[1], wc161);
  not gc161 (wc161, n_2187);
  nor g7209 (regs2_n_121, n_2190, i_reg2[0]);
  and g7210 (regs2_n_119, i_reg2[0], wc162);
  not gc162 (wc162, n_2190);
  and g7211 (regs2_n_125, i_reg2[1], wc163);
  not gc163 (wc163, n_2193);
  nor g7212 (regs2_n_129, n_2193, i_reg2[1]);
  nor g7213 (o_flag[2], n_2018, o_flag[0]);
  or g7214 (n_1950, wc164, n_2169);
  not gc164 (wc164, n_2168);
  or g7215 (n_1892, wc165, n_2109);
  not gc165 (wc165, n_2108);
  or g7216 (n_1912, wc166, n_2121);
  not gc166 (wc166, n_2120);
  or g7217 (n_1941, wc167, n_2157);
  not gc167 (wc167, n_2156);
  or g7218 (n_1933, wc168, n_2145);
  not gc168 (wc168, n_2144);
  or g7219 (n_1926, wc169, n_2133);
  not gc169 (wc169, n_2132);
  or g7220 (n_1960, wc170, n_2181);
  not gc170 (wc170, n_2180);
  or g7221 (n_1894, wc171, n_2430);
  not gc171 (wc171, n_2429);
  or g7222 (n_2063, wc172, n_2418);
  not gc172 (wc172, n_2417);
  or g7223 (n_2524, wc173, n_2520);
  not gc173 (wc173, n_2519);
  or g7224 (n_2751, wc174, n_1895);
  not gc174 (wc174, n_2063);
  or g7225 (n_2734, wc175, n_2730);
  not gc175 (wc175, n_2729);
  or g7226 (n_2476, wc176, n_2472);
  not gc176 (wc176, n_2471);
  or g7227 (n_2686, wc177, n_2682);
  not gc177 (wc177, n_2681);
  or g7228 (n_2572, wc178, n_2568);
  not gc178 (wc178, n_2567);
  or g7229 (n_3047, n_1966, wc179);
  not gc179 (wc179, n_1948);
  or g7230 (n_1897, n_1886, wc180);
  not gc180 (wc180, n_1896);
  or g7231 (n_2919, wc181, n_1935);
  not gc181 (wc181, n_1931);
  or g7232 (n_3014, n_1966, wc182);
  not gc182 (wc182, n_1907);
  or g7233 (n_2925, wc183, n_1943);
  not gc183 (wc183, n_1931);
  or g7234 (n_3023, n_1966, wc184);
  not gc184 (wc184, n_1924);
  or g7235 (n_2913, n_1885, wc185);
  not gc185 (wc185, n_1928);
  or g7236 (n_3038, n_1966, wc186);
  not gc186 (wc186, n_1937);
  or g7237 (n_3058, n_1966, wc187);
  not gc187 (wc187, n_1896);
  or g7238 (n_2987, n_2985, wc188);
  not gc188 (wc188, n_1896);
  or g7239 (n_3304, n_1884, wc189);
  not gc189 (wc189, n_1979);
  or g7240 (n_1958, n_1896, wc190);
  not gc190 (wc190, n_2964);
  or g7241 (n_2074, n_1884, wc191);
  not gc191 (wc191, n_1949);
  or g7242 (n_3027, wc192, n_1952);
  not gc192 (wc192, n_2074);
  or g7243 (n_3638, wc193, n_1940);
  not gc193 (wc193, n_2036);
  or g7244 (n_3639, n_2036, wc194);
  not gc194 (wc194, n_1940);
  or g7245 (n_2060, n_3015, wc195);
  not gc195 (wc195, n_1964);
  or g7246 (n_3249, wc196, n_1977);
  not gc196 (wc196, n_1975);
  or g7247 (n_2067, n_3024, wc197);
  not gc197 (wc197, n_1964);
  or g7248 (n_3279, wc198, n_1977);
  not gc198 (wc198, n_1963);
  or g7249 (n_3331, wc199, n_1977);
  not gc199 (wc199, n_1974);
  or g7250 (n_3247, wc200, n_1921);
  not gc200 (wc200, n_2060);
  or g7251 (n_3074, wc201, n_1982);
  not gc201 (wc201, n_1986);
  or g7252 (n_3277, wc202, n_1943);
  not gc202 (wc202, n_2067);
  or g7253 (n_3330, n_1884, wc203);
  not gc203 (wc203, n_1982);
  or g7254 (n_3352, n_2012, wc204);
  not gc204 (wc204, n_2042);
  or g7255 (n_3146, wc205, n_2022);
  not gc205 (wc205, n_1963);
  or g7256 (n_3636, wc206, n_1945);
  not gc206 (wc206, n_2035);
  or g7257 (n_3637, n_2035, wc207);
  not gc207 (wc207, n_1945);
  or g7258 (n_3251, wc208, n_2022);
  not gc208 (wc208, n_1974);
  or g7259 (n_3278, n_1884, wc209);
  not gc209 (wc209, n_1983);
  or g7260 (n_2024, n_1962, wc210);
  not gc210 (wc210, n_1983);
  or g7261 (n_3186, wc211, n_2022);
  not gc211 (wc211, n_1975);
  or g7262 (n_3248, n_1884, wc212);
  not gc212 (wc212, n_1978);
  or g7263 (n_3336, wc213, n_3334);
  not gc213 (wc213, n_3333);
  or g7264 (n_3143, n_1884, wc214);
  not gc214 (wc214, n_1954);
  or g7265 (n_3152, wc215, n_3149);
  not gc215 (wc215, n_3148);
  or g7266 (n_3184, n_1884, wc216);
  not gc216 (wc216, n_1973);
  or g7267 (n_3213, wc217, n_1981);
  not gc217 (wc217, n_2065);
  or g7268 (n_3223, wc218, n_1981);
  not gc218 (wc218, n_2071);
  or g7269 (n_3203, n_1962, wc219);
  not gc219 (wc219, n_2017);
  or g7270 (n_3204, wc220, n_2017);
  not gc220 (wc220, n_1980);
  or g7271 (n_3354, n_3352, wc221);
  not gc221 (wc221, o_flag[0]);
  or g7272 (n_3306, n_1897, wc222);
  not gc222 (wc222, n_1989);
  or g7273 (n_3250, n_1897, wc223);
  not gc223 (wc223, n_1984);
  or g7274 (n_3280, n_1897, wc224);
  not gc224 (wc224, n_1987);
  or g7275 (n_3309, wc225, n_3307);
  not gc225 (wc225, n_3306);
  or g7276 (n_3332, n_1897, wc226);
  not gc226 (wc226, n_1991);
  or g7277 (n_3353, wc227, n_1993);
  not gc227 (wc227, n_2056);
  CDN_flop regs2_RRR__1_0(.clk (regs2_rc_gclk), .d (i_data2[0]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_0));
  CDN_flop regs2_RRR__1_1(.clk (regs2_rc_gclk), .d (i_data2[1]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_1));
  CDN_flop regs2_RRR__1_2(.clk (regs2_rc_gclk), .d (i_data2[2]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_2));
  CDN_flop regs2_RRR__1_3(.clk (regs2_rc_gclk), .d (i_data2[3]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_3));
  CDN_flop regs2_RRR__1_4(.clk (regs2_rc_gclk), .d (i_data2[4]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_4));
  CDN_flop regs2_RRR__1_5(.clk (regs2_rc_gclk), .d (i_data2[5]), .sena
       (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (regs2_RRR_1_5));
  CDN_flop regs2_RRR__2_0(.clk (regs2_rc_gclk_304), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_0));
  CDN_flop regs2_RRR__2_1(.clk (regs2_rc_gclk_304), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_1));
  CDN_flop regs2_RRR__2_2(.clk (regs2_rc_gclk_304), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_2));
  CDN_flop regs2_RRR__2_3(.clk (regs2_rc_gclk_304), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_3));
  CDN_flop regs2_RRR__2_4(.clk (regs2_rc_gclk_304), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_4));
  CDN_flop regs2_RRR__2_5(.clk (regs2_rc_gclk_304), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_2_5));
  CDN_flop regs2_RRR__3_0(.clk (regs2_rc_gclk_302), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_0));
  CDN_flop regs2_RRR__3_1(.clk (regs2_rc_gclk_302), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_1));
  CDN_flop regs2_RRR__3_2(.clk (regs2_rc_gclk_302), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_2));
  CDN_flop regs2_RRR__3_3(.clk (regs2_rc_gclk_302), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_3));
  CDN_flop regs2_RRR__3_4(.clk (regs2_rc_gclk_302), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_4));
  CDN_flop regs2_RRR__3_5(.clk (regs2_rc_gclk_302), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_3_5));
  CDN_flop regs2_RRR__4_0(.clk (regs2_rc_gclk_300), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_0));
  CDN_flop regs2_RRR__4_1(.clk (regs2_rc_gclk_300), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_1));
  CDN_flop regs2_RRR__4_2(.clk (regs2_rc_gclk_300), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_2));
  CDN_flop regs2_RRR__4_3(.clk (regs2_rc_gclk_300), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_3));
  CDN_flop regs2_RRR__4_4(.clk (regs2_rc_gclk_300), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_4));
  CDN_flop regs2_RRR__4_5(.clk (regs2_rc_gclk_300), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_4_5));
  CDN_flop regs2_RRR__5_0(.clk (regs2_rc_gclk_298), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_0));
  CDN_flop regs2_RRR__5_1(.clk (regs2_rc_gclk_298), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_1));
  CDN_flop regs2_RRR__5_2(.clk (regs2_rc_gclk_298), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_2));
  CDN_flop regs2_RRR__5_3(.clk (regs2_rc_gclk_298), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_3));
  CDN_flop regs2_RRR__5_4(.clk (regs2_rc_gclk_298), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_4));
  CDN_flop regs2_RRR__5_5(.clk (regs2_rc_gclk_298), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_5_5));
  CDN_flop regs2_RRR__6_0(.clk (regs2_rc_gclk_296), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_0));
  CDN_flop regs2_RRR__6_1(.clk (regs2_rc_gclk_296), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_1));
  CDN_flop regs2_RRR__6_2(.clk (regs2_rc_gclk_296), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_2));
  CDN_flop regs2_RRR__6_3(.clk (regs2_rc_gclk_296), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_3));
  CDN_flop regs2_RRR__6_4(.clk (regs2_rc_gclk_296), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_4));
  CDN_flop regs2_RRR__6_5(.clk (regs2_rc_gclk_296), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_6_5));
  CDN_flop regs2_RRR__7_0(.clk (regs2_rc_gclk_294), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_0));
  CDN_flop regs2_RRR__7_1(.clk (regs2_rc_gclk_294), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_1));
  CDN_flop regs2_RRR__7_2(.clk (regs2_rc_gclk_294), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_2));
  CDN_flop regs2_RRR__7_3(.clk (regs2_rc_gclk_294), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_3));
  CDN_flop regs2_RRR__7_4(.clk (regs2_rc_gclk_294), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_4));
  CDN_flop regs2_RRR__7_5(.clk (regs2_rc_gclk_294), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_7_5));
  CDN_flop regs2_RRR__8_0(.clk (regs2_rc_gclk_292), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_0));
  CDN_flop regs2_RRR__8_1(.clk (regs2_rc_gclk_292), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_1));
  CDN_flop regs2_RRR__8_2(.clk (regs2_rc_gclk_292), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_2));
  CDN_flop regs2_RRR__8_3(.clk (regs2_rc_gclk_292), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_3));
  CDN_flop regs2_RRR__8_4(.clk (regs2_rc_gclk_292), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_4));
  CDN_flop regs2_RRR__8_5(.clk (regs2_rc_gclk_292), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_8_5));
  CDN_flop regs2_RRR__9_0(.clk (regs2_rc_gclk_290), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_0));
  CDN_flop regs2_RRR__9_1(.clk (regs2_rc_gclk_290), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_1));
  CDN_flop regs2_RRR__9_2(.clk (regs2_rc_gclk_290), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_2));
  CDN_flop regs2_RRR__9_3(.clk (regs2_rc_gclk_290), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_3));
  CDN_flop regs2_RRR__9_4(.clk (regs2_rc_gclk_290), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_4));
  CDN_flop regs2_RRR__9_5(.clk (regs2_rc_gclk_290), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_9_5));
  CDN_flop regs2_RRR__10_0(.clk (regs2_rc_gclk_288), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_0));
  CDN_flop regs2_RRR__10_1(.clk (regs2_rc_gclk_288), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_1));
  CDN_flop regs2_RRR__10_2(.clk (regs2_rc_gclk_288), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_2));
  CDN_flop regs2_RRR__10_3(.clk (regs2_rc_gclk_288), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_3));
  CDN_flop regs2_RRR__10_4(.clk (regs2_rc_gclk_288), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_4));
  CDN_flop regs2_RRR__10_5(.clk (regs2_rc_gclk_288), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_10_5));
  CDN_flop regs2_RRR__11_0(.clk (regs2_rc_gclk_286), .d (i_data2[0]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_0));
  CDN_flop regs2_RRR__11_1(.clk (regs2_rc_gclk_286), .d (i_data2[1]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_1));
  CDN_flop regs2_RRR__11_2(.clk (regs2_rc_gclk_286), .d (i_data2[2]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_2));
  CDN_flop regs2_RRR__11_3(.clk (regs2_rc_gclk_286), .d (i_data2[3]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_3));
  CDN_flop regs2_RRR__11_4(.clk (regs2_rc_gclk_286), .d (i_data2[4]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_4));
  CDN_flop regs2_RRR__11_5(.clk (regs2_rc_gclk_286), .d (i_data2[5]),
       .sena (1'b1), .aclr (n_1995), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (regs2_RRR_11_5));
  not regs2_g5371 (n_1995, i_rsn);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
