
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jan 16 2025 11:04:57 CET (Jan 16 2025 10:04:57 UTC)

// Verification Directory fv/EXE 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module EXE(i_oper, i_reg0, i_reg1, i_reg2, i_data2, i_data, i_imm,
     i_clk, i_rsn, o_flag, o_data);
  input [2:0] i_oper;
  input [3:0] i_reg0, i_reg1, i_reg2;
  input [5:0] i_data2, i_data;
  input i_imm, i_clk, i_rsn;
  output [3:0] o_flag;
  output [5:0] o_data;
  wire [2:0] i_oper;
  wire [3:0] i_reg0, i_reg1, i_reg2;
  wire [5:0] i_data2, i_data;
  wire i_imm, i_clk, i_rsn;
  wire [3:0] o_flag;
  wire [5:0] o_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, regs2_RRR_1_0, regs2_RRR_1_1, regs2_RRR_1_2,
       regs2_RRR_1_3, regs2_RRR_1_4, regs2_RRR_1_5, regs2_RRR_2_0;
  wire regs2_RRR_2_1, regs2_RRR_2_2, regs2_RRR_2_3, regs2_RRR_2_4,
       regs2_RRR_2_5, regs2_RRR_3_0, regs2_RRR_3_1, regs2_RRR_3_2;
  wire regs2_RRR_3_3, regs2_RRR_3_4, regs2_RRR_3_5, regs2_RRR_4_0,
       regs2_RRR_4_1, regs2_RRR_4_2, regs2_RRR_4_3, regs2_RRR_4_4;
  wire regs2_RRR_4_5, regs2_RRR_5_0, regs2_RRR_5_1, regs2_RRR_5_2,
       regs2_RRR_5_3, regs2_RRR_5_4, regs2_RRR_5_5, regs2_RRR_6_0;
  wire regs2_RRR_6_1, regs2_RRR_6_2, regs2_RRR_6_3, regs2_RRR_6_4,
       regs2_RRR_6_5, regs2_RRR_7_0, regs2_RRR_7_1, regs2_RRR_7_2;
  wire regs2_RRR_7_3, regs2_RRR_7_4, regs2_RRR_7_5, regs2_RRR_8_0,
       regs2_RRR_8_1, regs2_RRR_8_2, regs2_RRR_8_3, regs2_RRR_8_4;
  wire regs2_RRR_8_5, regs2_RRR_9_0, regs2_RRR_9_1, regs2_RRR_9_2,
       regs2_RRR_9_3, regs2_RRR_9_4, regs2_RRR_9_5, regs2_RRR_10_0;
  wire regs2_RRR_10_1, regs2_RRR_10_2, regs2_RRR_10_3, regs2_RRR_10_4,
       regs2_RRR_10_5, regs2_RRR_11_0, regs2_RRR_11_1, regs2_RRR_11_2;
  wire regs2_RRR_11_3, regs2_RRR_11_4, regs2_RRR_11_5, regs2_n_115,
       regs2_n_117, regs2_n_119, regs2_n_121, regs2_n_123;
  wire regs2_n_125, regs2_n_127, regs2_n_129, regs2_n_131, regs2_n_133,
       regs2_n_135, regs2_rc_gclk, regs2_rc_gclk_286;
  wire regs2_rc_gclk_288, regs2_rc_gclk_290, regs2_rc_gclk_292,
       regs2_rc_gclk_294, regs2_rc_gclk_296, regs2_rc_gclk_298,
       regs2_rc_gclk_300, regs2_rc_gclk_302;
  wire regs2_rc_gclk_304;
  assign o_data[5] = o_flag[0];
  RC_CG_MOD regs2_RC_CG_HIER_INST0(.enable (regs2_n_135), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk), .test (1'b0));
  RC_CG_MOD_1 regs2_RC_CG_HIER_INST1(.enable (regs2_n_115), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_286), .test (1'b0));
  RC_CG_MOD_2 regs2_RC_CG_HIER_INST2(.enable (regs2_n_117), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_288), .test (1'b0));
  RC_CG_MOD_3 regs2_RC_CG_HIER_INST3(.enable (regs2_n_119), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_290), .test (1'b0));
  RC_CG_MOD_4 regs2_RC_CG_HIER_INST4(.enable (regs2_n_121), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_292), .test (1'b0));
  RC_CG_MOD_5 regs2_RC_CG_HIER_INST5(.enable (regs2_n_123), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_294), .test (1'b0));
  RC_CG_MOD_6 regs2_RC_CG_HIER_INST6(.enable (regs2_n_125), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_296), .test (1'b0));
  RC_CG_MOD_7 regs2_RC_CG_HIER_INST7(.enable (regs2_n_127), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_298), .test (1'b0));
  RC_CG_MOD_8 regs2_RC_CG_HIER_INST8(.enable (regs2_n_129), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_300), .test (1'b0));
  RC_CG_MOD_9 regs2_RC_CG_HIER_INST9(.enable (regs2_n_131), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_302), .test (1'b0));
  RC_CG_MOD_10 regs2_RC_CG_HIER_INST10(.enable (regs2_n_133), .ck_in
       (i_clk), .ck_out (regs2_rc_gclk_304), .test (1'b0));
  DFRRQHDX1 regs2_RRR__1_0(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[0]), .Q (regs2_RRR_1_0));
  DFRRQHDX1 regs2_RRR__1_1(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[1]), .Q (regs2_RRR_1_1));
  DFRRQHDX1 regs2_RRR__1_2(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[2]), .Q (regs2_RRR_1_2));
  DFRRQHDX1 regs2_RRR__1_3(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[3]), .Q (regs2_RRR_1_3));
  DFRRQHDX1 regs2_RRR__1_4(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[4]), .Q (regs2_RRR_1_4));
  DFRRQHDX1 regs2_RRR__1_5(.RN (i_rsn), .C (regs2_rc_gclk), .D
       (i_data2[5]), .Q (regs2_RRR_1_5));
  DFRRQHDX1 regs2_RRR__2_0(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[0]), .Q (regs2_RRR_2_0));
  DFRRQHDX1 regs2_RRR__2_1(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[1]), .Q (regs2_RRR_2_1));
  DFRRQHDX1 regs2_RRR__2_2(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[2]), .Q (regs2_RRR_2_2));
  DFRRQHDX1 regs2_RRR__2_3(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[3]), .Q (regs2_RRR_2_3));
  DFRRQHDX1 regs2_RRR__2_4(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[4]), .Q (regs2_RRR_2_4));
  DFRRQHDX1 regs2_RRR__2_5(.RN (i_rsn), .C (regs2_rc_gclk_304), .D
       (i_data2[5]), .Q (regs2_RRR_2_5));
  DFRRQHDX1 regs2_RRR__3_0(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[0]), .Q (regs2_RRR_3_0));
  DFRRQHDX1 regs2_RRR__3_1(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[1]), .Q (regs2_RRR_3_1));
  DFRRQHDX1 regs2_RRR__3_2(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[2]), .Q (regs2_RRR_3_2));
  DFRRQHDX1 regs2_RRR__3_3(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[3]), .Q (regs2_RRR_3_3));
  DFRRQHDX1 regs2_RRR__3_4(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[4]), .Q (regs2_RRR_3_4));
  DFRRQHDX1 regs2_RRR__3_5(.RN (i_rsn), .C (regs2_rc_gclk_302), .D
       (i_data2[5]), .Q (regs2_RRR_3_5));
  DFRRQHDX1 regs2_RRR__4_0(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[0]), .Q (regs2_RRR_4_0));
  DFRRQHDX1 regs2_RRR__4_1(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[1]), .Q (regs2_RRR_4_1));
  DFRRQHDX1 regs2_RRR__4_2(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[2]), .Q (regs2_RRR_4_2));
  DFRRQHDX1 regs2_RRR__4_3(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[3]), .Q (regs2_RRR_4_3));
  DFRRQHDX1 regs2_RRR__4_4(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[4]), .Q (regs2_RRR_4_4));
  DFRRQHDX1 regs2_RRR__4_5(.RN (i_rsn), .C (regs2_rc_gclk_300), .D
       (i_data2[5]), .Q (regs2_RRR_4_5));
  DFRRQHDX1 regs2_RRR__5_0(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[0]), .Q (regs2_RRR_5_0));
  DFRRQHDX1 regs2_RRR__5_1(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[1]), .Q (regs2_RRR_5_1));
  DFRRQHDX1 regs2_RRR__5_2(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[2]), .Q (regs2_RRR_5_2));
  DFRRQHDX1 regs2_RRR__5_3(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[3]), .Q (regs2_RRR_5_3));
  DFRRQHDX1 regs2_RRR__5_4(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[4]), .Q (regs2_RRR_5_4));
  DFRRQHDX1 regs2_RRR__5_5(.RN (i_rsn), .C (regs2_rc_gclk_298), .D
       (i_data2[5]), .Q (regs2_RRR_5_5));
  DFRRQHDX1 regs2_RRR__6_0(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[0]), .Q (regs2_RRR_6_0));
  DFRRQHDX1 regs2_RRR__6_1(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[1]), .Q (regs2_RRR_6_1));
  DFRRQHDX1 regs2_RRR__6_2(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[2]), .Q (regs2_RRR_6_2));
  DFRRQHDX1 regs2_RRR__6_3(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[3]), .Q (regs2_RRR_6_3));
  DFRRQHDX1 regs2_RRR__6_4(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[4]), .Q (regs2_RRR_6_4));
  DFRRQHDX1 regs2_RRR__6_5(.RN (i_rsn), .C (regs2_rc_gclk_296), .D
       (i_data2[5]), .Q (regs2_RRR_6_5));
  DFRRQHDX1 regs2_RRR__7_0(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[0]), .Q (regs2_RRR_7_0));
  DFRRQHDX1 regs2_RRR__7_1(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[1]), .Q (regs2_RRR_7_1));
  DFRRQHDX1 regs2_RRR__7_2(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[2]), .Q (regs2_RRR_7_2));
  DFRRQHDX1 regs2_RRR__7_3(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[3]), .Q (regs2_RRR_7_3));
  DFRRQHDX1 regs2_RRR__7_4(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[4]), .Q (regs2_RRR_7_4));
  DFRRQHDX1 regs2_RRR__7_5(.RN (i_rsn), .C (regs2_rc_gclk_294), .D
       (i_data2[5]), .Q (regs2_RRR_7_5));
  DFRRQHDX1 regs2_RRR__8_0(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[0]), .Q (regs2_RRR_8_0));
  DFRRQHDX1 regs2_RRR__8_1(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[1]), .Q (regs2_RRR_8_1));
  DFRRQHDX1 regs2_RRR__8_2(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[2]), .Q (regs2_RRR_8_2));
  DFRRQHDX1 regs2_RRR__8_3(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[3]), .Q (regs2_RRR_8_3));
  DFRRQHDX1 regs2_RRR__8_4(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[4]), .Q (regs2_RRR_8_4));
  DFRRQHDX1 regs2_RRR__8_5(.RN (i_rsn), .C (regs2_rc_gclk_292), .D
       (i_data2[5]), .Q (regs2_RRR_8_5));
  DFRRQHDX1 regs2_RRR__9_0(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[0]), .Q (regs2_RRR_9_0));
  DFRRQHDX1 regs2_RRR__9_1(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[1]), .Q (regs2_RRR_9_1));
  DFRRQHDX1 regs2_RRR__9_2(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[2]), .Q (regs2_RRR_9_2));
  DFRRQHDX1 regs2_RRR__9_3(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[3]), .Q (regs2_RRR_9_3));
  DFRRQHDX1 regs2_RRR__9_4(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[4]), .Q (regs2_RRR_9_4));
  DFRRQHDX1 regs2_RRR__9_5(.RN (i_rsn), .C (regs2_rc_gclk_290), .D
       (i_data2[5]), .Q (regs2_RRR_9_5));
  DFRRQHDX1 regs2_RRR__10_0(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[0]), .Q (regs2_RRR_10_0));
  DFRRQHDX1 regs2_RRR__10_1(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[1]), .Q (regs2_RRR_10_1));
  DFRRQHDX1 regs2_RRR__10_2(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[2]), .Q (regs2_RRR_10_2));
  DFRRQHDX1 regs2_RRR__10_3(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[3]), .Q (regs2_RRR_10_3));
  DFRRQHDX1 regs2_RRR__10_4(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[4]), .Q (regs2_RRR_10_4));
  DFRRQHDX1 regs2_RRR__10_5(.RN (i_rsn), .C (regs2_rc_gclk_288), .D
       (i_data2[5]), .Q (regs2_RRR_10_5));
  DFRRQHDX1 regs2_RRR__11_0(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[0]), .Q (regs2_RRR_11_0));
  DFRRQHDX1 regs2_RRR__11_1(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[1]), .Q (regs2_RRR_11_1));
  DFRRQHDX1 regs2_RRR__11_2(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[2]), .Q (regs2_RRR_11_2));
  DFRRQHDX1 regs2_RRR__11_3(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[3]), .Q (regs2_RRR_11_3));
  DFRRQHDX1 regs2_RRR__11_4(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[4]), .Q (regs2_RRR_11_4));
  DFRRQHDX1 regs2_RRR__11_5(.RN (i_rsn), .C (regs2_rc_gclk_286), .D
       (i_data2[5]), .Q (regs2_RRR_11_5));
  AO31HDX2 g13655__2398(.A (n_131), .B (n_195), .C (o_flag[1]), .D
       (n_234), .Q (o_flag[3]));
  NO2HDX4 g13656__5107(.A (n_240), .B (n_228), .Q (o_flag[1]));
  AND2HDX2 g13657__6260(.A (n_240), .B (n_230), .Q (o_flag[2]));
  NO5HDX1 g13658__4319(.A (o_data[3]), .B (o_data[2]), .C (o_data[1]),
       .D (o_data[0]), .E (o_data[4]), .Q (n_240));
  AO321HDX2 g13659__8428(.A (n_8), .B (n_126), .C (n_140), .D (n_3), .E
       (n_212), .F (n_238), .Q (o_data[3]));
  AO321HDX2 g13660__5526(.A (n_8), .B (n_124), .C (n_128), .D (n_3), .E
       (n_203), .F (n_239), .Q (o_data[2]));
  ON211HDX0 g13661__6783(.A (n_156), .B (n_188), .C (n_237), .D
       (n_206), .Q (n_239));
  ON211HDX0 g13662__3680(.A (n_157), .B (n_188), .C (n_235), .D
       (n_201), .Q (n_238));
  AO221HDX2 g13663__1617(.A (n_3), .B (n_179), .C (n_30), .D (n_152),
       .E (n_236), .Q (o_data[0]));
  ON221HDX2 g13664__2802(.A (n_161), .B (n_188), .C (n_143), .D
       (n_232), .E (n_214), .Q (o_data[1]));
  AN22HDX1 g13665__1705(.A (n_233), .B (n_144), .C (n_183), .D (n_172),
       .Q (n_237));
  ON222HDX0 g13666__5122(.A (n_194), .B (n_136), .C (n_143), .D
       (n_227), .E (n_7), .F (n_170), .Q (n_236));
  AN22HDX1 g13667__8246(.A (n_231), .B (n_144), .C (n_183), .D (n_160),
       .Q (n_235));
  NO5I3HDX1 g13668__7098(.AN (n_229), .BN (n_149), .CN (n_169), .D
       (n_192), .E (n_131), .Q (n_234));
  AO221HDX1 g13669__6131(.A (n_207), .B (n_224), .C (n_131), .D
       (n_208), .E (n_225), .Q (n_233));
  AN211HDX1 g13670__1881(.A (n_224), .B (n_202), .C (n_210), .D
       (n_225), .Q (n_232));
  MU2HDX0 g13671__5115(.IN0 (n_131), .IN1 (n_191), .S (n_226), .Q
       (n_231));
  INHDX3 g13672(.A (n_230), .Q (o_flag[0]));
  INHDX1 g13673(.A (n_230), .Q (n_229));
  INHDX1 g13674(.A (n_230), .Q (n_228));
  OA311HDX1 g13675__7482(.A (n_7), .B (n_123), .C (n_131), .D (n_182),
       .E (n_221), .Q (n_230));
  AN211HDX1 g13676__4733(.A (n_210), .B (n_200), .C (n_222), .D
       (n_225), .Q (n_227));
  NO2I1HDX1 g13677__6161(.AN (n_224), .B (n_198), .Q (n_226));
  AO221HDX2 g13678__9315(.A (n_127), .B (n_187), .C (n_131), .D
       (n_144), .E (n_223), .Q (o_data[4]));
  AND2HDX1 g13679__9945(.A (n_219), .B (n_131), .Q (n_225));
  NO2HDX1 g13680__2883(.A (n_219), .B (n_203), .Q (n_224));
  ON21HDX1 g13681__2346(.A (n_177), .B (n_178), .C (n_220), .Q (n_223));
  AN211HDX1 g13682__1666(.A (n_198), .B (n_190), .C (n_213), .D
       (n_219), .Q (n_222));
  AN211HDX1 g13683__7410(.A (n_217), .B (n_3), .C (n_193), .D (n_209),
       .Q (n_221));
  AN321HDX0 g13684__6417(.A (n_139), .B (n_133), .C (n_8), .D (n_155),
       .E (n_183), .F (n_218), .Q (n_220));
  NA3I2HDX1 g13685__5477(.AN (n_217), .BN (n_212), .C (n_215), .Q
       (n_219));
  ON22HDX0 g13686__2398(.A (n_2), .B (n_215), .C (n_133), .D (n_199),
       .Q (n_218));
  EN3HDX0 g13687__5107(.A (n_216), .B (n_168), .C (n_141), .Q (n_217));
  OA22HDX1 g13688__6260(.A (n_211), .B (n_175), .C (n_166), .D (n_133),
       .Q (n_216));
  EO2HDX1 g13689__4319(.A (n_211), .B (n_185), .Q (n_215));
  AN321HDX0 g13690__8428(.A (n_125), .B (n_134), .C (n_8), .D (n_3), .E
       (n_198), .F (n_205), .Q (n_214));
  AO32HDX1 g13691__5526(.A (n_134), .B (n_189), .C (n_197), .D (n_189),
       .E (n_203), .Q (n_213));
  EN2HDX0 g13692__6783(.A (n_204), .B (n_180), .Q (n_212));
  CAGHDX1 g13693__3680(.A (n_126), .B (n_164), .CI (n_204), .CO
       (n_211));
  AND2HDX1 g13694__1617(.A (n_203), .B (n_131), .Q (n_210));
  AN31HDX1 g13695__2802(.A (n_143), .B (n_145), .C (n_194), .D (n_130),
       .Q (n_209));
  AO21HDX1 g13696__1705(.A (n_198), .B (n_179), .C (n_203), .Q (n_208));
  ON21HDX1 g13697__5122(.A (n_198), .B (n_190), .C (n_189), .Q (n_207));
  AO21HDX1 g13698__8246(.A (n_194), .B (n_147), .C (n_128), .Q (n_206));
  AN21HDX1 g13699__7098(.A (n_194), .B (n_148), .C (n_134), .Q (n_205));
  MU2HDX0 g13700__6131(.IN0 (n_129), .IN1 (n_191), .S (n_198), .Q
       (n_202));
  NA22HDX1 g13701__1881(.A (n_194), .B (n_158), .C (n_127), .Q (n_201));
  AN22HDX1 g13702__5115(.A (n_196), .B (n_173), .C (n_165), .D (n_129),
       .Q (n_204));
  EO2HDX1 g13703__7482(.A (n_181), .B (n_196), .Q (n_203));
  OR2HDX1 g13704__4733(.A (n_198), .B (n_179), .Q (n_200));
  NO2I1HDX0 g13705__6161(.AN (n_194), .B (n_154), .Q (n_199));
  INHDX1 g13706(.A (n_198), .Q (n_197));
  FAHDX0 g13707__9315(.A (n_162), .B (n_167), .CI (n_142), .CO (n_196),
       .S (n_198));
  MU2IHDX1 g13708__9945(.IN0 (n_123), .IN1 (n_186), .S (i_oper[0]), .Q
       (n_195));
  ON22HDX0 g13709__2883(.A (n_157), .B (n_184), .C (n_133), .D (n_188),
       .Q (n_193));
  AN32HDX1 g13710__2346(.A (n_37), .B (n_123), .C (n_177), .D (n_1), .E
       (n_8), .Q (n_194));
  NO22HDX0 g13711__1666(.A (n_177), .B (n_2), .C (i_oper[0]), .Q
       (n_192));
  MU2IHDX1 g13712__7410(.IN0 (n_126), .IN1 (n_133), .S (n_179), .Q
       (n_191));
  MU2IHDX1 g13713__6417(.IN0 (n_129), .IN1 (n_127), .S (n_179), .Q
       (n_190));
  INHDX1 g13714(.A (n_188), .Q (n_187));
  OR2HDX0 g13715__5477(.A (n_177), .B (i_oper[1]), .Q (n_186));
  NO2HDX1 g13716__2398(.A (n_176), .B (n_175), .Q (n_185));
  OR2HDX1 g13717__5107(.A (n_179), .B (n_133), .Q (n_189));
  NA3I2HDX1 g13718__6260(.AN (n_177), .BN (n_171), .C (n_37), .Q
       (n_188));
  INHDX1 g13719(.A (n_183), .Q (n_184));
  NA5I3HDX1 g13720__4319(.AN (n_177), .BN (n_161), .CN (n_159), .D
       (n_124), .E (n_37), .Q (n_182));
  ON31HDX0 g13721__8428(.A (n_128), .B (n_2), .C (n_165), .D (n_174),
       .Q (n_181));
  ON32HDX0 g13722__5526(.A (n_2), .B (n_126), .C (n_163), .D (n_127),
       .E (n_164), .Q (n_180));
  NO5I3HDX1 g13723__6783(.AN (n_153), .BN (n_37), .CN (n_125), .D
       (n_177), .E (n_124), .Q (n_183));
  NA3I1HDX1 g13724__3680(.AN (n_159), .B (n_172), .C (n_37), .Q
       (n_178));
  NA22HDX1 g13725__1617(.A (n_172), .B (n_3), .C (n_146), .Q (n_179));
  AN21HDX1 g13726__2802(.A (n_166), .B (n_3), .C (n_133), .Q (n_176));
  ON21HDX1 g13727__1705(.A (n_171), .B (n_137), .C (n_123), .Q (n_177));
  AND2HDX1 g13728__5122(.A (n_166), .B (n_133), .Q (n_175));
  NA2HDX1 g13729__8246(.A (n_165), .B (n_128), .Q (n_174));
  AO21HDX1 g13730__7098(.A (n_129), .B (n_3), .C (n_165), .Q (n_173));
  HAHDX0 g13731__6131(.A (n_138), .B (n_135), .CO (n_172), .S (n_170));
  NA5I3HDX1 g13732__1881(.AN (n_127), .BN (n_129), .CN (n_132), .D
       (n_134), .E (n_136), .Q (n_169));
  EN2HDX0 g13733__5115(.A (n_151), .B (n_123), .Q (n_168));
  OR2HDX1 g13734__7482(.A (n_159), .B (n_124), .Q (n_171));
  AO22HDX1 g13735__4733(.A (n_150), .B (n_138), .C (n_152), .D (n_3),
       .Q (n_167));
  INHDX1 g13736(.A (n_164), .Q (n_163));
  EO2HDX1 g13737__6161(.A (n_150), .B (n_125), .Q (n_162));
  EO2HDX1 g13738__9315(.A (n_151), .B (n_139), .Q (n_166));
  EO2HDX1 g13739__9945(.A (n_150), .B (n_124), .Q (n_165));
  EO2HDX1 g13740__2883(.A (n_151), .B (n_140), .Q (n_164));
  INHDX1 g13741(.A (n_161), .Q (n_160));
  MU2IHDX1 g13742__2346(.IN0 (n_8), .IN1 (n_30), .S (n_140), .Q
       (n_158));
  NO22HDX0 g13743__1666(.A (n_137), .B (n_134), .C (n_152), .Q (n_161));
  NA2I1HDX1 g13744__7410(.AN (n_125), .B (n_153), .Q (n_159));
  INHDX1 g13745(.A (n_155), .Q (n_156));
  MU2HDX0 g13746__6417(.IN0 (n_8), .IN1 (n_30), .S (n_139), .Q (n_154));
  MU2IHDX1 g13747__5477(.IN0 (n_129), .IN1 (n_127), .S (n_138), .Q
       (n_157));
  MU2IHDX1 g13748__2398(.IN0 (n_128), .IN1 (n_134), .S (n_137), .Q
       (n_155));
  INHDX1 g13749(.A (n_151), .Q (n_150));
  ON21HDX1 g13750__5107(.A (n_123), .B (i_oper[2]), .C (i_oper[0]), .Q
       (n_149));
  NO2HDX1 g13751__6260(.A (n_140), .B (n_139), .Q (n_153));
  NO2HDX1 g13752__4319(.A (n_138), .B (n_136), .Q (n_152));
  NO2HDX1 g13753__8428(.A (n_144), .B (i_oper[0]), .Q (n_151));
  MU2IHDX1 g13754__5526(.IN0 (n_8), .IN1 (n_30), .S (n_125), .Q
       (n_148));
  MU2IHDX0 g13755__6783(.IN0 (n_8), .IN1 (n_30), .S (n_124), .Q
       (n_147));
  ON21HDX1 g13756__3680(.A (n_136), .B (n_2), .C (n_137), .Q (n_146));
  MU2IHDX1 g13757__1617(.IN0 (n_30), .IN1 (n_8), .S (n_123), .Q
       (n_145));
  INHDX1 g13758(.A (n_144), .Q (n_143));
  NO2HDX1 g13759__2802(.A (n_134), .B (n_2), .Q (n_142));
  NA2HDX1 g13760__1705(.A (n_131), .B (n_3), .Q (n_141));
  NO2I1HDX1 g13761__5122(.AN (n_37), .B (n_123), .Q (n_144));
  INHDX1 g13762(.A (n_138), .Q (n_137));
  AO221HDX1 g13763__8246(.A (n_71), .B (regs2_RRR_1_3), .C (n_69), .D
       (regs2_RRR_3_3), .E (n_121), .Q (n_140));
  AO221HDX1 g13764__7098(.A (n_67), .B (regs2_RRR_4_4), .C (n_73), .D
       (regs2_RRR_6_4), .E (n_122), .Q (n_139));
  AN221HDX0 g13765__6131(.A (n_69), .B (regs2_RRR_3_0), .C (n_73), .D
       (regs2_RRR_6_0), .E (n_120), .Q (n_138));
  INHDX1 g13766(.A (n_136), .Q (n_135));
  INHDX1 g13767(.A (n_133), .Q (n_132));
  INHDX1 g13768(.A (n_131), .Q (n_130));
  INHDX1 g13769(.A (n_129), .Q (n_128));
  INHDX1 g13770(.A (n_127), .Q (n_126));
  NA3I2HDX1 g13771__1881(.AN (n_107), .BN (n_81), .C (n_19), .Q
       (n_136));
  NA3I2HDX1 g13772__5115(.AN (n_109), .BN (n_78), .C (n_19), .Q
       (n_134));
  NA3I2HDX1 g13773__7482(.AN (n_110), .BN (n_80), .C (n_19), .Q
       (n_133));
  NO3HDX1 g13774__4733(.A (n_111), .B (n_84), .C (n_18), .Q (n_131));
  NO3HDX1 g13775__6161(.A (n_108), .B (n_79), .C (n_18), .Q (n_129));
  NO3HDX1 g13776__9315(.A (n_112), .B (n_83), .C (n_18), .Q (n_127));
  AO221HDX0 g13777__9945(.A (n_71), .B (regs2_RRR_1_4), .C (n_69), .D
       (regs2_RRR_3_4), .E (n_115), .Q (n_122));
  AO221HDX0 g13778__2883(.A (n_67), .B (regs2_RRR_4_3), .C (n_73), .D
       (regs2_RRR_6_3), .E (n_116), .Q (n_121));
  AO221HDX0 g13779__2346(.A (n_71), .B (regs2_RRR_1_0), .C (n_67), .D
       (regs2_RRR_4_0), .E (n_117), .Q (n_120));
  AO221HDX1 g13780__1666(.A (n_68), .B (regs2_RRR_2_1), .C (n_73), .D
       (regs2_RRR_6_1), .E (n_118), .Q (n_125));
  AO221HDX1 g13781__7410(.A (n_68), .B (regs2_RRR_2_2), .C (n_73), .D
       (regs2_RRR_6_2), .E (n_119), .Q (n_124));
  AN221HDX0 g13782__6417(.A (i_imm), .B (i_data[5]), .C (n_33), .D
       (n_85), .E (n_106), .Q (n_123));
  NA22HDX1 g13783__5477(.A (regs2_RRR_4_2), .B (n_67), .C (n_114), .Q
       (n_119));
  NA22HDX1 g13784__2398(.A (regs2_RRR_4_1), .B (n_67), .C (n_113), .Q
       (n_118));
  AO221HDX0 g13785__5107(.A (n_68), .B (regs2_RRR_2_0), .C (n_72), .D
       (regs2_RRR_5_0), .E (n_101), .Q (n_117));
  AO221HDX0 g13786__6260(.A (n_68), .B (regs2_RRR_2_3), .C (n_72), .D
       (regs2_RRR_5_3), .E (n_102), .Q (n_116));
  AO221HDX0 g13787__4319(.A (n_72), .B (regs2_RRR_5_4), .C (n_74), .D
       (regs2_RRR_7_4), .E (n_105), .Q (n_115));
  AN221HDX1 g13788__8428(.A (n_71), .B (regs2_RRR_1_2), .C (i_imm), .D
       (i_data[2]), .E (n_104), .Q (n_114));
  AN221HDX1 g13789__5526(.A (n_71), .B (regs2_RRR_1_1), .C (i_imm), .D
       (i_data[1]), .E (n_103), .Q (n_113));
  ON221HDX0 g13790__6783(.A (regs2_RRR_10_3), .B (n_39), .C (n_40), .D
       (regs2_RRR_9_3), .E (n_97), .Q (n_112));
  ON221HDX0 g13791__3680(.A (regs2_RRR_11_5), .B (n_36), .C (n_38), .D
       (regs2_RRR_8_5), .E (n_96), .Q (n_111));
  ON221HDX0 g13792__1617(.A (regs2_RRR_10_4), .B (n_39), .C (n_38), .D
       (regs2_RRR_8_4), .E (n_94), .Q (n_110));
  ON221HDX0 g13793__2802(.A (regs2_RRR_10_1), .B (n_39), .C (n_40), .D
       (regs2_RRR_9_1), .E (n_95), .Q (n_109));
  ON221HDX0 g13794__1705(.A (regs2_RRR_8_2), .B (n_38), .C (n_36), .D
       (regs2_RRR_11_2), .E (n_93), .Q (n_108));
  ON221HDX0 g13795__5122(.A (regs2_RRR_9_0), .B (n_40), .C (n_39), .D
       (regs2_RRR_10_0), .E (n_100), .Q (n_107));
  ON22HDX0 g13796__8246(.A (n_32), .B (n_99), .C (n_31), .D (n_98), .Q
       (n_106));
  AO221HDX0 g13797__7098(.A (i_imm), .B (i_data[4]), .C (n_68), .D
       (regs2_RRR_2_4), .E (n_90), .Q (n_105));
  ON321HDX0 g13798__6131(.A (n_55), .B (n_31), .C (n_58), .D (n_70), .E
       (n_28), .F (n_89), .Q (n_104));
  ON321HDX0 g13799__1881(.A (n_54), .B (n_31), .C (n_53), .D (n_70), .E
       (n_29), .F (n_88), .Q (n_103));
  AO221HDX0 g13800__5115(.A (n_74), .B (regs2_RRR_7_3), .C (i_imm), .D
       (i_data[3]), .E (n_91), .Q (n_102));
  AO221HDX0 g13801__7482(.A (n_74), .B (regs2_RRR_7_0), .C (i_imm), .D
       (i_data[0]), .E (n_92), .Q (n_101));
  AN32HDX1 g13802__4733(.A (i_reg0[2]), .B (n_64), .C (n_63), .D
       (n_20), .E (n_86), .Q (n_100));
  AN222HDX1 g13803__6161(.A (n_16), .B (regs2_RRR_4_5), .C (i_reg1[1]),
       .D (n_43), .E (n_13), .F (regs2_RRR_5_5), .Q (n_99));
  AN222HDX1 g13804__9315(.A (n_9), .B (regs2_RRR_11_5), .C (n_0), .D
       (n_44), .E (n_11), .F (regs2_RRR_10_5), .Q (n_98));
  AN32HDX1 g13805__9945(.A (i_reg0[2]), .B (n_56), .C (n_60), .D
       (n_20), .E (n_75), .Q (n_97));
  AN32HDX1 g13806__2883(.A (i_reg0[2]), .B (n_57), .C (n_59), .D
       (n_20), .E (n_87), .Q (n_96));
  AN32HDX1 g13807__2346(.A (i_reg0[2]), .B (n_45), .C (n_46), .D
       (n_20), .E (n_82), .Q (n_95));
  AN32HDX1 g13808__1666(.A (i_reg0[2]), .B (n_49), .C (n_52), .D
       (n_20), .E (n_77), .Q (n_94));
  AN32HDX1 g13809__7410(.A (i_reg0[2]), .B (n_65), .C (n_66), .D
       (n_20), .E (n_76), .Q (n_93));
  NO3HDX1 g13810__6417(.A (n_61), .B (n_62), .C (n_31), .Q (n_92));
  NO3HDX1 g13811__5477(.A (n_50), .B (n_51), .C (n_31), .Q (n_91));
  NO3HDX1 g13812__2398(.A (n_47), .B (n_48), .C (n_31), .Q (n_90));
  AN22HDX1 g13813__5107(.A (regs2_RRR_5_2), .B (n_72), .C (n_74), .D
       (regs2_RRR_7_2), .Q (n_89));
  AN22HDX1 g13814__6260(.A (regs2_RRR_5_1), .B (n_72), .C (n_74), .D
       (regs2_RRR_7_1), .Q (n_88));
  AN222HDX0 g13815__4319(.A (regs2_RRR_1_5), .B (n_5), .C
       (regs2_RRR_3_5), .D (n_6), .E (n_4), .F (regs2_RRR_2_5), .Q
       (n_87));
  AN222HDX1 g13816__8428(.A (n_6), .B (regs2_RRR_3_0), .C (n_4), .D
       (regs2_RRR_2_0), .E (n_5), .F (regs2_RRR_1_0), .Q (n_86));
  AO222HDX0 g13817__5526(.A (n_11), .B (regs2_RRR_2_5), .C (n_13), .D
       (regs2_RRR_1_5), .E (n_9), .F (regs2_RRR_3_5), .Q (n_85));
  ON22HDX0 g13818__6783(.A (n_39), .B (regs2_RRR_10_5), .C (n_40), .D
       (regs2_RRR_9_5), .Q (n_84));
  ON22HDX0 g13819__3680(.A (n_38), .B (regs2_RRR_8_3), .C (n_36), .D
       (regs2_RRR_11_3), .Q (n_83));
  AN222HDX1 g13820__1617(.A (n_6), .B (regs2_RRR_3_1), .C (n_4), .D
       (regs2_RRR_2_1), .E (n_5), .F (regs2_RRR_1_1), .Q (n_82));
  ON22HDX0 g13821__2802(.A (n_38), .B (regs2_RRR_8_0), .C (n_36), .D
       (regs2_RRR_11_0), .Q (n_81));
  ON22HDX0 g13822__1705(.A (n_40), .B (regs2_RRR_9_4), .C (n_36), .D
       (regs2_RRR_11_4), .Q (n_80));
  ON22HDX0 g13823__5122(.A (n_39), .B (regs2_RRR_10_2), .C (n_40), .D
       (regs2_RRR_9_2), .Q (n_79));
  ON22HDX0 g13824__8246(.A (n_38), .B (regs2_RRR_8_1), .C (n_36), .D
       (regs2_RRR_11_1), .Q (n_78));
  AN222HDX1 g13825__7098(.A (n_5), .B (regs2_RRR_1_4), .C (n_6), .D
       (regs2_RRR_3_4), .E (n_4), .F (regs2_RRR_2_4), .Q (n_77));
  AN222HDX0 g13826__6131(.A (regs2_RRR_3_2), .B (n_6), .C
       (regs2_RRR_2_2), .D (n_4), .E (n_5), .F (regs2_RRR_1_2), .Q
       (n_76));
  AN222HDX0 g13827__1881(.A (regs2_RRR_3_3), .B (n_6), .C
       (regs2_RRR_2_3), .D (n_4), .E (n_5), .F (regs2_RRR_1_3), .Q
       (n_75));
  INHDX1 g13828(.A (n_70), .Q (n_69));
  NO2HDX0 g13829__5115(.A (i_reg2[1]), .B (n_41), .Q (regs2_n_129));
  NO2I1HDX0 g13830__7482(.AN (i_reg2[0]), .B (n_35), .Q (regs2_n_115));
  NO2HDX0 g13831__4733(.A (i_reg2[0]), .B (n_35), .Q (regs2_n_117));
  NO2HDX0 g13832__6161(.A (i_reg2[1]), .B (n_42), .Q (regs2_n_127));
  NO2I1HDX0 g13833__9315(.AN (i_reg2[0]), .B (n_34), .Q (regs2_n_119));
  NO2I1HDX0 g13834__9945(.AN (i_reg2[1]), .B (n_41), .Q (regs2_n_125));
  NO2I1HDX0 g13835__2883(.AN (i_reg2[1]), .B (n_42), .Q (regs2_n_123));
  NO2HDX0 g13836__2346(.A (i_reg2[0]), .B (n_34), .Q (regs2_n_121));
  AN22HDX1 g13837__1666(.A (regs2_RRR_6_2), .B (n_4), .C
       (regs2_RRR_7_2), .D (n_6), .Q (n_66));
  AN22HDX1 g13838__7410(.A (regs2_RRR_4_2), .B (n_15), .C
       (regs2_RRR_5_2), .D (n_5), .Q (n_65));
  AN22HDX1 g13839__6417(.A (regs2_RRR_6_0), .B (n_4), .C
       (regs2_RRR_7_0), .D (n_6), .Q (n_64));
  AN22HDX1 g13840__5477(.A (regs2_RRR_4_0), .B (n_15), .C
       (regs2_RRR_5_0), .D (n_5), .Q (n_63));
  NO2I1HDX1 g13841__2398(.AN (n_9), .B (n_32), .Q (n_74));
  NO2I1HDX1 g13842__5107(.AN (n_11), .B (n_32), .Q (n_73));
  NO2I1HDX1 g13843__6260(.AN (n_13), .B (n_32), .Q (n_72));
  AND2HDX1 g13844__4319(.A (n_33), .B (n_13), .Q (n_71));
  NA2HDX1 g13845__8428(.A (n_33), .B (n_9), .Q (n_70));
  AND2HDX1 g13846__5526(.A (n_33), .B (n_11), .Q (n_68));
  NO2I1HDX1 g13847__6783(.AN (n_16), .B (n_32), .Q (n_67));
  ON22HDX0 g13848__3680(.A (n_12), .B (regs2_RRR_10_0), .C (n_10), .D
       (regs2_RRR_11_0), .Q (n_62));
  ON22HDX0 g13849__1617(.A (n_17), .B (regs2_RRR_8_0), .C (n_14), .D
       (regs2_RRR_9_0), .Q (n_61));
  AN22HDX1 g13850__2802(.A (regs2_RRR_6_3), .B (n_4), .C
       (regs2_RRR_7_3), .D (n_6), .Q (n_60));
  AN22HDX1 g13851__1705(.A (regs2_RRR_6_5), .B (n_4), .C
       (regs2_RRR_7_5), .D (n_6), .Q (n_59));
  ON22HDX0 g13852__5122(.A (n_17), .B (regs2_RRR_8_2), .C (n_14), .D
       (regs2_RRR_9_2), .Q (n_58));
  AN22HDX1 g13853__8246(.A (regs2_RRR_4_5), .B (n_15), .C
       (regs2_RRR_5_5), .D (n_5), .Q (n_57));
  AN22HDX1 g13854__7098(.A (regs2_RRR_4_3), .B (n_15), .C
       (regs2_RRR_5_3), .D (n_5), .Q (n_56));
  ON22HDX0 g13855__6131(.A (n_12), .B (regs2_RRR_10_2), .C (n_10), .D
       (regs2_RRR_11_2), .Q (n_55));
  ON22HDX0 g13856__1881(.A (n_12), .B (regs2_RRR_10_1), .C (n_10), .D
       (regs2_RRR_11_1), .Q (n_54));
  ON22HDX0 g13857__5115(.A (n_17), .B (regs2_RRR_8_1), .C (n_14), .D
       (regs2_RRR_9_1), .Q (n_53));
  AN22HDX1 g13858__7482(.A (regs2_RRR_6_4), .B (n_4), .C
       (regs2_RRR_7_4), .D (n_6), .Q (n_52));
  ON22HDX0 g13859__4733(.A (n_12), .B (regs2_RRR_10_3), .C (n_10), .D
       (regs2_RRR_11_3), .Q (n_51));
  ON22HDX0 g13860__6161(.A (n_17), .B (regs2_RRR_8_3), .C (n_14), .D
       (regs2_RRR_9_3), .Q (n_50));
  AN22HDX1 g13861__9315(.A (regs2_RRR_4_4), .B (n_15), .C
       (regs2_RRR_5_4), .D (n_5), .Q (n_49));
  ON22HDX0 g13862__9945(.A (n_12), .B (regs2_RRR_10_4), .C (n_10), .D
       (regs2_RRR_11_4), .Q (n_48));
  ON22HDX0 g13863__2883(.A (n_17), .B (regs2_RRR_8_4), .C (n_14), .D
       (regs2_RRR_9_4), .Q (n_47));
  AN22HDX1 g13864__2346(.A (regs2_RRR_6_1), .B (n_4), .C
       (regs2_RRR_7_1), .D (n_6), .Q (n_46));
  AN22HDX1 g13865__1666(.A (regs2_RRR_4_1), .B (n_15), .C
       (regs2_RRR_5_1), .D (n_5), .Q (n_45));
  MU2HDX0 g13866__7410(.IN0 (regs2_RRR_8_5), .IN1 (regs2_RRR_9_5), .S
       (i_reg1[0]), .Q (n_44));
  MU2HDX0 g13867__6417(.IN0 (regs2_RRR_6_5), .IN1 (regs2_RRR_7_5), .S
       (i_reg1[0]), .Q (n_43));
  NO2I1HDX0 g13868__5477(.AN (n_25), .B (n_22), .Q (regs2_n_135));
  NA2HDX0 g13869__2398(.A (n_21), .B (i_reg2[2]), .Q (n_42));
  NA2HDX0 g13870__5107(.A (n_26), .B (i_reg2[2]), .Q (n_41));
  NA2HDX1 g13871__6260(.A (n_5), .B (i_reg0[3]), .Q (n_40));
  NA2HDX1 g13872__4319(.A (n_4), .B (i_reg0[3]), .Q (n_39));
  NA2HDX1 g13873__8428(.A (n_15), .B (i_reg0[3]), .Q (n_38));
  NO2HDX1 g13874__5526(.A (n_27), .B (i_oper[0]), .Q (n_37));
  NA2HDX1 g13875__6783(.A (n_6), .B (i_reg0[3]), .Q (n_36));
  NO2HDX0 g13876__3680(.A (n_23), .B (n_22), .Q (regs2_n_131));
  NO2I1HDX0 g13877__1617(.AN (n_26), .B (n_23), .Q (regs2_n_133));
  NA2HDX0 g13878__2802(.A (n_24), .B (i_reg2[3]), .Q (n_35));
  NA2HDX0 g13879__1705(.A (n_25), .B (i_reg2[3]), .Q (n_34));
  NO3HDX1 g13880__5122(.A (i_imm), .B (i_reg1[3]), .C (i_reg1[2]), .Q
       (n_33));
  NA3I2HDX1 g13881__8246(.AN (i_imm), .BN (i_reg1[3]), .C (i_reg1[2]),
       .Q (n_32));
  NA3I2HDX1 g13882__7098(.AN (i_imm), .BN (i_reg1[2]), .C (i_reg1[3]),
       .Q (n_31));
  NO2HDX1 g13883__6131(.A (n_27), .B (n_1), .Q (n_30));
  INHDX1 g13884(.A (regs2_RRR_3_1), .Q (n_29));
  INHDX1 g13926(.A (regs2_RRR_3_2), .Q (n_28));
  INHDX1 g13927(.A (n_23), .Q (n_24));
  INHDX1 g13928(.A (n_22), .Q (n_21));
  INHDX1 g13929(.A (n_19), .Q (n_18));
  INHDX1 g13930(.A (n_17), .Q (n_16));
  INHDX1 g13931(.A (n_14), .Q (n_13));
  INHDX1 g13932(.A (n_12), .Q (n_11));
  INHDX1 g13933(.A (n_10), .Q (n_9));
  INHDX1 g13934(.A (n_8), .Q (n_7));
  INHDX1 g13935(.A (n_3), .Q (n_2));
  NA2I1HDX1 g13961__1881(.AN (i_oper[2]), .B (i_oper[1]), .Q (n_27));
  NO2HDX0 g13962__5115(.A (i_reg2[0]), .B (i_reg2[3]), .Q (n_26));
  NO2HDX0 g13963__7482(.A (i_reg2[1]), .B (i_reg2[2]), .Q (n_25));
  NA2I1HDX0 g13964__4733(.AN (i_reg2[2]), .B (i_reg2[1]), .Q (n_23));
  NA2I1HDX0 g13965__6161(.AN (i_reg2[3]), .B (i_reg2[0]), .Q (n_22));
  NO2HDX1 g13966__9315(.A (i_reg0[3]), .B (i_reg0[2]), .Q (n_20));
  NA2HDX1 g13967__9945(.A (i_reg0[2]), .B (i_reg0[3]), .Q (n_19));
  NA2I1HDX1 g13968__2883(.AN (i_reg1[0]), .B (n_0), .Q (n_17));
  NO2HDX1 g13969__2346(.A (i_reg0[1]), .B (i_reg0[0]), .Q (n_15));
  NA2HDX1 g13970__1666(.A (n_0), .B (i_reg1[0]), .Q (n_14));
  NA2I1HDX1 g13971__7410(.AN (i_reg1[0]), .B (i_reg1[1]), .Q (n_12));
  NA2HDX1 g13972__6417(.A (i_reg1[1]), .B (i_reg1[0]), .Q (n_10));
  NO2I1HDX0 g13973__5477(.AN (i_oper[2]), .B (i_oper[1]), .Q (n_8));
  AND2HDX1 g13974__2398(.A (i_reg0[1]), .B (i_reg0[0]), .Q (n_6));
  NO2I1HDX0 g13975__5107(.AN (i_reg0[0]), .B (i_reg0[1]), .Q (n_5));
  NO2I1HDX0 g13976__6260(.AN (i_reg0[1]), .B (i_reg0[0]), .Q (n_4));
  NO2HDX1 g13977__4319(.A (i_oper[2]), .B (i_oper[1]), .Q (n_3));
  INHDX0 g13978(.A (i_oper[0]), .Q (n_1));
  INHDX0 g13979(.A (i_reg1[1]), .Q (n_0));
endmodule

