
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jan 16 2025 10:46:42 CET (Jan 16 2025 09:46:42 UTC)

// Verification Directory fv/ALU 

module ALU(i_arg0, i_arg1, i_oper, i_data, i_imm, o_result, o_flag);
  input [5:0] i_arg0, i_arg1, i_data;
  input [2:0] i_oper;
  input i_imm;
  output [5:0] o_result;
  output [3:0] o_flag;
  wire [5:0] i_arg0, i_arg1, i_data;
  wire [2:0] i_oper;
  wire i_imm;
  wire [5:0] o_result;
  wire [3:0] o_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_101, n_102, n_103, n_104;
  wire n_105, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_116, n_120;
  AO33HDX2 g4216__2398(.A (n_23), .B (n_60), .C (o_flag[1]), .D (n_6),
       .E (n_3), .F (n_112), .Q (o_flag[3]));
  AND2HDX2 g4217__5107(.A (n_120), .B (n_102), .Q (o_flag[1]));
  NO2HDX4 g4218__6260(.A (n_120), .B (n_104), .Q (o_flag[2]));
  OR5HDX1 g4219__4319(.A (o_result[2]), .B (o_result[1]), .C
       (o_result[3]), .D (o_result[0]), .E (o_result[4]), .Q (n_120));
  AO221HDX2 g4220__8428(.A (n_28), .B (n_72), .C (i_arg0[2]), .D
       (n_66), .E (n_116), .Q (o_result[2]));
  AO211HDX2 g4221__5526(.A (n_67), .B (i_arg0[1]), .C (n_79), .D
       (n_114), .Q (o_result[1]));
  ON221HDX2 g4222__6783(.A (n_26), .B (n_109), .C (n_38), .D (n_63), .E
       (n_92), .Q (o_result[3]));
  ON321HDX0 g4223__3680(.A (n_9), .B (i_arg0[2]), .C (n_15), .D (n_26),
       .E (n_111), .F (n_85), .Q (n_116));
  AO221HDX2 g4224__1617(.A (n_6), .B (n_34), .C (n_11), .D (n_29), .E
       (n_113), .Q (o_result[0]));
  ON32HDX0 g4225__2802(.A (i_arg0[1]), .B (n_9), .C (n_18), .D (n_26),
       .E (n_110), .Q (n_114));
  AO222HDX1 g4226__1705(.A (i_arg0[0]), .B (n_64), .C (n_27), .D
       (n_108), .E (n_8), .F (n_28), .Q (n_113));
  AN211HDX1 g4227__5122(.A (n_13), .B (i_oper[0]), .C (n_61), .D
       (n_103), .Q (n_112));
  OA211HDX0 g4228__8246(.A (n_98), .B (n_75), .C (n_99), .D (n_83), .Q
       (n_111));
  OA211HDX0 g4229__7098(.A (n_98), .B (n_76), .C (n_99), .D (n_83), .Q
       (n_110));
  MU2HDX0 g4230__6131(.IN0 (n_3), .IN1 (n_52), .S (n_101), .Q (n_109));
  ON221HDX0 g4231__1881(.A (n_96), .B (n_88), .C (n_70), .D (n_83), .E
       (n_99), .Q (n_108));
  INHDX3 g4232(.A (n_105), .Q (o_result[5]));
  INHDX3 g4233(.A (n_105), .Q (o_flag[0]));
  INHDX1 g4234(.A (n_104), .Q (n_105));
  INHDX1 g4235(.A (n_104), .Q (n_103));
  INHDX1 g4236(.A (n_104), .Q (n_102));
  NA4I2HDX1 g4237__5115(.AN (n_95), .BN (n_65), .C (n_82), .D (n_80),
       .Q (n_104));
  NO2HDX1 g4238__7482(.A (n_98), .B (n_71), .Q (n_101));
  AO321HDX2 g4239__4733(.A (n_28), .B (n_36), .C (n_57), .D (n_40), .E
       (n_72), .F (n_97), .Q (o_result[4]));
  NA2HDX1 g4240__6161(.A (n_96), .B (i_arg0[5]), .Q (n_99));
  ON221HDX0 g4241__9315(.A (n_63), .B (n_0), .C (n_3), .D (n_26), .E
       (n_94), .Q (n_97));
  NA2I1HDX1 g4242__9945(.AN (n_96), .B (n_78), .Q (n_98));
  NA3HDX1 g4243__2883(.A (n_93), .B (n_90), .C (n_86), .Q (n_96));
  ON32HDX0 g4244__2346(.A (i_arg0[5]), .B (n_9), .C (n_13), .D (n_5),
       .E (n_93), .Q (n_95));
  OA321HDX1 g4245__1666(.A (i_arg0[4]), .B (n_9), .C (n_16), .D (n_5),
       .E (n_90), .F (n_73), .Q (n_94));
  EN3HDX0 g4246__7410(.A (n_91), .B (n_48), .C (n_23), .Q (n_93));
  AN221HDX1 g4247__6417(.A (n_37), .B (n_72), .C (i_arg0[3]), .D
       (n_68), .E (n_89), .Q (n_92));
  CAGHDX1 g4248__5477(.A (i_arg0[4]), .B (n_43), .CI (n_87), .CO
       (n_91));
  ON32HDX0 g4249__2398(.A (i_arg0[3]), .B (n_9), .C (n_17), .D (n_5),
       .E (n_86), .Q (n_89));
  EO2HDX1 g4250__5107(.A (n_87), .B (n_59), .Q (n_90));
  AN22HDX1 g4251__6260(.A (n_74), .B (n_78), .C (n_84), .D (n_70), .Q
       (n_88));
  CAGHDX1 g4252__4319(.A (i_arg0[3]), .B (n_42), .CI (n_81), .CO
       (n_87));
  AN22HDX1 g4253__8428(.A (n_77), .B (n_6), .C (n_62), .D (n_40), .Q
       (n_85));
  EO2HDX1 g4254__5526(.A (n_81), .B (n_58), .Q (n_86));
  NO2HDX1 g4255__6783(.A (n_78), .B (n_51), .Q (n_84));
  AN22HDX1 g4256__3680(.A (n_72), .B (n_39), .C (n_62), .D (i_arg0[4]),
       .Q (n_82));
  NA2HDX1 g4257__1617(.A (n_77), .B (i_arg0[5]), .Q (n_83));
  ON31HDX0 g4258__2802(.A (n_30), .B (n_27), .C (n_64), .D (i_arg0[5]),
       .Q (n_80));
  AO22HDX1 g4259__1705(.A (n_71), .B (n_6), .C (n_62), .D (n_37), .Q
       (n_79));
  NA22HDX1 g4260__5122(.A (n_69), .B (n_54), .C (n_55), .Q (n_81));
  INHDX1 g4261(.A (n_78), .Q (n_77));
  MU2HDX0 g4262__8246(.IN0 (n_1), .IN1 (n_52), .S (n_71), .Q (n_76));
  MU2HDX0 g4263__7098(.IN0 (n_50), .IN1 (n_51), .S (n_71), .Q (n_75));
  MU2HDX0 g4264__6131(.IN0 (i_arg0[1]), .IN1 (n_49), .S (n_71), .Q
       (n_74));
  EO2HDX1 g4265__1881(.A (n_56), .B (n_69), .Q (n_78));
  ON21HDX1 g4266__5115(.A (n_64), .B (n_32), .C (i_arg0[4]), .Q (n_73));
  NO5I4HDX1 g4267__7482(.AN (n_57), .BN (n_17), .CN (n_15), .DN (n_16),
       .E (n_18), .Q (n_72));
  INHDX1 g4268(.A (n_71), .Q (n_70));
  FAHDX0 g4269__4733(.A (n_47), .B (n_46), .CI (n_19), .CO (n_69), .S
       (n_71));
  OR2HDX1 g4270__6161(.A (n_64), .B (n_31), .Q (n_68));
  OR2HDX1 g4271__9315(.A (n_64), .B (n_33), .Q (n_67));
  AO221HDX1 g4272__9945(.A (n_22), .B (n_14), .C (n_8), .D (n_15), .E
       (n_64), .Q (n_66));
  NO4I3HDX0 g4273__2883(.AN (n_57), .BN (n_37), .CN (n_36), .D (n_15),
       .Q (n_65));
  AO32HDX1 g4274__2346(.A (n_13), .B (n_24), .C (n_53), .D (n_4), .E
       (n_8), .Q (n_64));
  INHDX1 g4275(.A (n_63), .Q (n_62));
  NA2HDX1 g4276__1666(.A (n_57), .B (n_41), .Q (n_63));
  AO32HDX1 g4277__7410(.A (n_1), .B (n_0), .C (n_10), .D (n_4), .E
       (n_53), .Q (n_61));
  MU2IHDX1 g4278__6417(.IN0 (n_53), .IN1 (n_13), .S (n_4), .Q (n_60));
  MU2HDX0 g4279__5477(.IN0 (n_20), .IN1 (i_arg0[4]), .S (n_43), .Q
       (n_59));
  MU2HDX0 g4280__2398(.IN0 (n_21), .IN1 (i_arg0[3]), .S (n_42), .Q
       (n_58));
  NA2HDX1 g4281__5107(.A (n_54), .B (n_55), .Q (n_56));
  NO2I1HDX1 g4282__6260(.AN (n_24), .B (n_53), .Q (n_57));
  NA2HDX1 g4283__4319(.A (n_44), .B (i_arg0[2]), .Q (n_55));
  ON21HDX1 g4284__8428(.A (n_5), .B (n_1), .C (n_45), .Q (n_54));
  NA22HDX1 g4285__5526(.A (n_41), .B (n_12), .C (n_13), .Q (n_53));
  INHDX1 g4286(.A (n_49), .Q (n_50));
  MU2IHDX1 g4287__6783(.IN0 (i_arg0[3]), .IN1 (i_arg0[4]), .S (n_34),
       .Q (n_52));
  MU2IHDX1 g4288__3680(.IN0 (i_arg0[4]), .IN1 (i_arg0[5]), .S (n_34),
       .Q (n_51));
  MU2IHDX1 g4289__1617(.IN0 (n_1), .IN1 (n_0), .S (n_34), .Q (n_49));
  EO2HDX1 g4290__2802(.A (n_35), .B (n_13), .Q (n_48));
  EO2HDX0 g4291__1705(.A (n_18), .B (n_35), .Q (n_47));
  MU2IHDX1 g4292__5122(.IN0 (n_35), .IN1 (n_25), .S (n_11), .Q (n_46));
  INHDX1 g4293(.A (n_44), .Q (n_45));
  EO2HDX1 g4294__8246(.A (n_35), .B (n_15), .Q (n_44));
  EO2HDX1 g4295__7098(.A (n_35), .B (n_16), .Q (n_43));
  EO2HDX1 g4296__6131(.A (n_35), .B (n_17), .Q (n_42));
  AND2HDX1 g4297__1881(.A (n_36), .B (n_15), .Q (n_41));
  INHDX1 g4298(.A (n_38), .Q (n_39));
  MU2HDX0 g4299__5115(.IN0 (i_arg0[1]), .IN1 (i_arg0[2]), .S (n_12), .Q
       (n_40));
  MU2IHDX1 g4300__7482(.IN0 (i_arg0[2]), .IN1 (i_arg0[3]), .S (n_12),
       .Q (n_38));
  MU2HDX0 g4301__4733(.IN0 (i_arg0[0]), .IN1 (i_arg0[1]), .S (n_12), .Q
       (n_37));
  AND3HDX1 g4302__6161(.A (n_18), .B (n_16), .C (n_17), .Q (n_36));
  NO2HDX1 g4303__9315(.A (n_27), .B (i_oper[0]), .Q (n_35));
  MU2HDX0 g4304__9945(.IN0 (n_22), .IN1 (n_8), .S (n_18), .Q (n_33));
  MU2HDX0 g4305__2883(.IN0 (n_22), .IN1 (n_8), .S (n_16), .Q (n_32));
  MU2HDX0 g4306__2346(.IN0 (n_22), .IN1 (n_8), .S (n_17), .Q (n_31));
  MU2HDX0 g4307__1666(.IN0 (n_22), .IN1 (n_8), .S (n_13), .Q (n_30));
  MU2HDX0 g4308__7410(.IN0 (n_8), .IN1 (n_22), .S (i_arg0[0]), .Q
       (n_29));
  EO2HDX1 g4309__6417(.A (n_12), .B (n_25), .Q (n_34));
  AND2HDX1 g4310__5477(.A (n_12), .B (i_arg0[0]), .Q (n_28));
  INHDX1 g4311(.A (n_27), .Q (n_26));
  NO2I1HDX1 g4312__2398(.AN (n_24), .B (n_13), .Q (n_27));
  NA2HDX1 g4313__5107(.A (n_6), .B (i_arg0[3]), .Q (n_21));
  NA2HDX1 g4314__6260(.A (n_6), .B (i_arg0[4]), .Q (n_20));
  AND2HDX1 g4315__4319(.A (n_6), .B (i_arg0[1]), .Q (n_19));
  NA2HDX1 g4316__8428(.A (n_6), .B (i_arg0[0]), .Q (n_25));
  NO2HDX1 g4317__5526(.A (n_7), .B (i_oper[0]), .Q (n_24));
  NO2HDX1 g4318__6783(.A (n_5), .B (n_3), .Q (n_23));
  NO2HDX1 g4319__3680(.A (n_7), .B (n_4), .Q (n_22));
  INHDX1 g4320(.A (n_15), .Q (n_14));
  INHDX1 g4321(.A (n_12), .Q (n_11));
  NO3HDX1 g4322__1617(.A (i_arg0[4]), .B (i_arg0[1]), .C (i_arg0[0]),
       .Q (n_10));
  MU2IHDX1 g4323__2802(.IN0 (i_arg1[1]), .IN1 (i_data[1]), .S (i_imm),
       .Q (n_18));
  MU2IHDX1 g4324__1705(.IN0 (i_arg1[3]), .IN1 (i_data[3]), .S (i_imm),
       .Q (n_17));
  MU2IHDX1 g4325__5122(.IN0 (i_arg1[4]), .IN1 (i_data[4]), .S (i_imm),
       .Q (n_16));
  AN22HDX1 g4326__8246(.A (n_2), .B (i_arg1[2]), .C (i_data[2]), .D
       (i_imm), .Q (n_15));
  MU2IHDX1 g4327__7098(.IN0 (i_arg1[5]), .IN1 (i_data[5]), .S (i_imm),
       .Q (n_13));
  MU2IHDX0 g4328__6131(.IN0 (i_arg1[0]), .IN1 (i_data[0]), .S (i_imm),
       .Q (n_12));
  INHDX1 g4329(.A (n_9), .Q (n_8));
  NA2I1HDX1 g4330__1881(.AN (i_oper[1]), .B (i_oper[2]), .Q (n_9));
  INHDX1 g4331(.A (n_6), .Q (n_5));
  NA2I1HDX1 g4332__5115(.AN (i_oper[2]), .B (i_oper[1]), .Q (n_7));
  NO2HDX1 g4333__7482(.A (i_oper[2]), .B (i_oper[1]), .Q (n_6));
  INHDX0 g4334(.A (i_oper[0]), .Q (n_4));
  INHDX0 g4335(.A (i_arg0[5]), .Q (n_3));
  INHDX0 g4336(.A (i_imm), .Q (n_2));
  INHDX0 g4337(.A (i_arg0[2]), .Q (n_1));
  INHDX0 g4338(.A (i_arg0[3]), .Q (n_0));
endmodule

